import{ConflictException,Inject,Injectable,NotFoundException}from'@nestjs/common';
import type{PeriodReopenDecisionInput,PeriodReopenRequestInput}from'@ledgerly/contracts';
import{decidePeriodReopen,TaxPeriodError}from'@ledgerly/domain';
import{randomUUID}from'node:crypto';
import type{RequestContext}from'../../organization/application/organization.service.js';
import{LEDGER_SETUP_STORE,type LedgerSetupStore}from'./ledger-setup-store.js';
import{PERIOD_REOPEN_STORE,type PeriodReopenStore}from'./period-reopen-store.js';
import{ReviewCaseIntakeService}from'../../review-case/application/review-case-intake.service.js';

@Injectable()
export class PeriodReopenService{
  constructor(@Inject(LEDGER_SETUP_STORE)private readonly setups:LedgerSetupStore,@Inject(PERIOD_REOPEN_STORE)private readonly requests:PeriodReopenStore,private readonly reviewIntake:ReviewCaseIntakeService){}
  async request(companyId:string,input:PeriodReopenRequestInput,context:RequestContext){if(!context.tenantId)throw new NotFoundException('Accounting period not found');const setup=await this.setups.find(context.tenantId,companyId);if(!setup)throw new NotFoundException('Accounting period not found');if(setup.periodStatus!=='locked')throw new ConflictException({code:'ACCOUNTING_PERIOD_NOT_LOCKED',message:'Only a locked accounting period can be reopened'});const occurredAt=new Date(),result=await this.requests.save({id:randomUUID(),tenantId:context.tenantId,companyId,periodId:setup.periodId,periodStart:setup.periodStart,periodEnd:setup.periodEnd,reason:input.reason,actorId:context.actorId,traceId:context.traceId,requestedAt:occurredAt});await this.reviewIntake.capture({tenantId:context.tenantId,companyId,sourceType:'period_reopen_request',sourceId:result.request.id,riskLevel:'red',blocksFiling:true,summary:`反结账申请：${result.request.reason}`,createdBy:result.request.requestedBy,traceId:context.traceId,occurredAt});return result;}
  async list(companyId:string,context:RequestContext){if(!context.tenantId)throw new NotFoundException('Company not found');return this.requests.list(context.tenantId,companyId);}
  async decide(companyId:string,requestId:string,input:PeriodReopenDecisionInput,context:RequestContext){if(!context.tenantId)throw new NotFoundException('Period reopen request not found');const current=await this.requests.find(context.tenantId,companyId,requestId);if(!current)throw new NotFoundException('Period reopen request not found');if(current.version!==input.expectedVersion)throw new ConflictException({code:'PERIOD_REOPEN_REQUEST_CHANGED',message:'Period reopen request has changed'});let status:'approved'|'rejected';try{status=decidePeriodReopen({status:current.status,requestedBy:current.requestedBy,decidedBy:context.actorId,decision:input.decision,reason:input.reason});}catch(error){if(error instanceof TaxPeriodError)throw new ConflictException({code:'PERIOD_REOPEN_DECISION_REJECTED',message:error.message});throw error;}const decided=await this.requests.decide({tenantId:context.tenantId,companyId,requestId,periodId:current.periodId,expectedVersion:input.expectedVersion,status,reason:input.reason.trim(),actorId:context.actorId,traceId:context.traceId,occurredAt:new Date()});if(!decided)throw new ConflictException({code:'PERIOD_REOPEN_REQUEST_CHANGED',message:'Period reopen request or period has changed'});return decided;}
}
