import{describe,expect,it}from'vitest';
import{assertReconciliationTriageTransition,BusinessEventStatus,BusinessEventType,createBusinessEvent,createInvoice,createSettlement,InvoiceColor,InvoiceDirection,InvoiceKind,InvoiceStatus,ReconciliationIssueTriageStatus,runReconciliationChecks}from'../src/index.js';
const invoice={...createInvoice({direction:InvoiceDirection.Output,kind:InvoiceKind.Ordinary,color:InvoiceColor.Blue,invoiceNumber:'12345678',issuedOn:'2026-10-08',counterpartyId:'party',amountExcludingTax:'100',taxAmount:'6',totalAmount:'106'}),status:InvoiceStatus.Confirmed,version:2};
const payment={...createBusinessEvent({type:BusinessEventType.MoneyReceived,occurredOn:'2026-10-09',amount:'80',counterpartyId:'party',description:'收款'}),status:BusinessEventStatus.Confirmed,version:2};
describe('reconciliation',()=>{
  it('allows a partial allocation within both remaining balances',()=>{expect(createSettlement({invoiceId:'i',paymentEventId:'p',amount:'60',invoice,paymentEvent:payment,invoiceAllocated:'20',paymentAllocated:'0'}).amount.toString()).toBe('60.00')});
  it('rejects direction, counterparty and over-allocation conflicts',()=>{expect(()=>createSettlement({invoiceId:'i',paymentEventId:'p',amount:'81',invoice,paymentEvent:payment,invoiceAllocated:'0',paymentAllocated:'0'})).toThrow('payment');expect(()=>createSettlement({invoiceId:'i',paymentEventId:'p',amount:'1',invoice,paymentEvent:{...payment,counterpartyId:'other'},invoiceAllocated:'0',paymentAllocated:'0'})).toThrow('counterparty');expect(()=>createSettlement({invoiceId:'i',paymentEventId:'p',amount:'1',invoice,paymentEvent:{...payment,type:BusinessEventType.MoneyPaid},invoiceAllocated:'0',paymentAllocated:'0'})).toThrow('direction')});
  it('returns every open reconciliation difference and only clears after facts are fixed',()=>{const result=runReconciliationChecks({invoices:[{invoiceId:'invoice-1',invoiceNumber:'12345678',outstandingAmount:'26'}],payments:[{paymentEventId:'payment-1',description:'客户收款',unallocatedAmount:'10'}]});expect(result).toMatchObject({grade:'yellow',blocksFiling:true,totalIssues:2,yellowIssues:2,redIssues:0});expect(result.issues.map(item=>item.code)).toEqual(['INVOICE_OUTSTANDING','PAYMENT_UNALLOCATED']);expect(runReconciliationChecks({invoices:[{invoiceId:'invoice-1',invoiceNumber:'12345678',outstandingAmount:'0'}],payments:[]})).toMatchObject({grade:'green',blocksFiling:false,totalIssues:0})});
  it('blocks filing when account rollforward or trial balance is broken',()=>{const result=runReconciliationChecks({periodId:'period-1',invoices:[],payments:[],accounts:[{accountCode:'1002',accountName:'银行存款',openingDebit:'100',openingCredit:'0',debitMovement:'20',creditMovement:'10',endingDebit:'109',endingCredit:'0'}]});expect(result).toMatchObject({grade:'red',blocksFiling:true,totalIssues:2,yellowIssues:0,redIssues:2});expect(result.issues.map(item=>item.code).sort()).toEqual(['ACCOUNT_BALANCE_ROLLFORWARD_MISMATCH','TRIAL_BALANCE_UNBALANCED'])});
  it('accepts a balanced account rollforward',()=>{expect(runReconciliationChecks({periodId:'period-1',invoices:[],payments:[],accounts:[{accountCode:'1002',accountName:'银行存款',openingDebit:'100',openingCredit:'0',debitMovement:'20',creditMovement:'10',endingDebit:'110',endingCredit:'0'},{accountCode:'3001',accountName:'实收资本',openingDebit:'0',openingCredit:'100',debitMovement:'10',creditMovement:'20',endingDebit:'0',endingCredit:'110'}]})).toMatchObject({grade:'green',blocksFiling:false,totalIssues:0})});
  it('allows investigation workflow without treating triage as resolution',()=>{expect(()=>assertReconciliationTriageTransition(ReconciliationIssueTriageStatus.Open,ReconciliationIssueTriageStatus.ReadyForRecheck)).toThrow('Invalid');expect(()=>assertReconciliationTriageTransition(ReconciliationIssueTriageStatus.Open,ReconciliationIssueTriageStatus.Investigating)).not.toThrow();expect(()=>assertReconciliationTriageTransition(ReconciliationIssueTriageStatus.Investigating,ReconciliationIssueTriageStatus.ReadyForRecheck)).not.toThrow()});
});
