'use client';
import { calculationRunListResponseSchema,calculationRunResponseSchema,type CalculationRunResponse } from '@ledgerly/contracts';
import { useEffect,useState,type FormEvent } from 'react';

interface WorkspaceContext{tenantId:string;companyId:string}
const decisionLabels={SCOPE_PROFILE_MISSING:'缺少适用性画像',SCOPE_NOT_ELIGIBLE:'当前主体不在自动化范围',NO_CONFIRMED_FACTS:'期间内没有已确认事实',NO_MATCHING_RULE:'没有匹配的活动规则',MULTIPLE_MATCHING_RULES:'存在多个匹配规则',IMPLEMENTATION_NOT_REGISTERED:'计算实现尚未注册'} as const;
const taxLabels={vat:'增值税',surcharge:'附加税费',corporate_income_tax:'企业所得税',stamp_duty:'印花税'} as const;
function workspace():WorkspaceContext|null{try{const raw:unknown=JSON.parse(window.localStorage.getItem('ledgerly.context')??'null');if(typeof raw!=='object'||raw===null)return null;const value=raw as Partial<WorkspaceContext>;return typeof value.tenantId==='string'&&typeof value.companyId==='string'?{tenantId:value.tenantId,companyId:value.companyId}:null}catch{return null}}
function endpoint(companyId:string){return`${process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001'}/v1/companies/${companyId}/calculation-runs`}
function headers(context:WorkspaceContext,json=false){return{'x-user-id':'10000000-0000-4000-8000-000000000001','x-tenant-id':context.tenantId,...(json?{'content-type':'application/json'}:{})}}

export function CalculationReadiness(){
  const[runs,setRuns]=useState<CalculationRunResponse[]>([]),[ready,setReady]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState<string|null>(null);
  async function load(context:WorkspaceContext){const response=await fetch(endpoint(context.companyId),{headers:headers(context)});if(!response.ok)throw new Error('无法读取准备检查记录。');setRuns(calculationRunListResponseSchema.parse(await response.json()).items)}
  useEffect(()=>{const context=workspace();if(!context){setReady(true);return}void load(context).catch(error=>setMessage(error instanceof Error?error.message:'读取失败。')).finally(()=>setReady(true))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const context=workspace();if(!context){setMessage('请先完成企业建档。');return}const form=new FormData(event.currentTarget);setPending(true);setMessage('正在冻结当前事实并检查全部前置条件…');try{const response=await fetch(endpoint(context.companyId),{method:'POST',headers:headers(context,true),body:JSON.stringify({taxType:form.get('taxType'),periodStart:form.get('periodStart'),periodEnd:form.get('periodEnd')})});const payload:unknown=await response.json();if(!response.ok)throw new Error('准备检查失败。');const run=calculationRunResponseSchema.parse(payload);setRuns(current=>[run,...current]);setMessage(run.status==='ready'?'全部前置条件已通过，可以进入确定性计算。':decisionLabels[run.decision!.code])}catch(error:unknown){setMessage(error instanceof Error?error.message:'准备检查失败。')}finally{setPending(false)}}
  if(!ready)return <section className="onboarding-card">正在读取试算准备状态…</section>;
  return <section className="governance-grid"><form className="onboarding-card governance-form" onSubmit={event=>void submit(event)}><h2>运行准备检查</h2><label>税种<select name="taxType" defaultValue="vat">{Object.entries(taxLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="governance-dates two"><label>期间开始<input name="periodStart" type="date" defaultValue="2026-10-01" required/></label><label>期间结束<input name="periodEnd" type="date" defaultValue="2026-12-31" required/></label></div><div className="notice">本操作只生成不可变输入快照和就绪度证据。实现未注册或专业样本未形成可发布规则时，不会输出税额。</div><button className="primary button" disabled={pending}>{pending?'检查中…':'冻结输入并检查'}</button>{message&&<p className={message.includes('通过')?'form-success':'form-error'}>{message}</p>}</form><section><div className="list-title"><div><p className="eyebrow">不可变运行记录</p><h2>准备检查轨迹</h2></div><span>{runs.length} 次</span></div>{runs.length===0?<p className="empty">尚未运行准备检查。</p>:runs.map(run=><article key={run.id} className="version-card"><header><div><strong>{taxLabels[run.taxType]}</strong><small>{run.periodStart} 至 {run.periodEnd}</small></div><span className={`rule-status ${run.status}`}>{run.status==='ready'?'已就绪':'已阻断'}</span></header>{run.decision&&<p className="form-error">{decisionLabels[run.decision.code]}：{run.decision.message}</p>}<ol>{run.steps.map(step=><li key={step.key}><strong>{step.status==='passed'?'✓':'!'} {step.key}</strong><small>{step.explanation}</small></li>)}</ol><details><summary>查看输入与规则哈希</summary><code>{run.inputHash}</code>{run.ruleContentHash&&<code>{run.ruleContentHash}</code>}</details></article>)}</section></section>
}
