import{ConflictException,Inject,Injectable,NotFoundException}from'@nestjs/common';
import type{FilingCalendarInput,FilingSopInput,FilingTaskGenerationInput,FilingTaskTransitionInput}from'@ledgerly/contracts';
import{assertFilingCalendarSource,deriveFilingTaskTiming,FilingError,transitionFilingTask}from'@ledgerly/domain';
import{createHash,randomUUID}from'node:crypto';
import{ORGANIZATION_STORE,type OrganizationStore}from'../../organization/application/organization-store.js';
import type{RequestContext}from'../../organization/application/organization.service.js';
import{FILING_STORE,type FilingCalendar,type FilingSop,type FilingStore,type FilingTask}from'./filing-store.js';

@Injectable()
export class FilingService{
  constructor(@Inject(FILING_STORE)private readonly store:FilingStore,@Inject(ORGANIZATION_STORE)private readonly organizations:OrganizationStore){}
  async createCalendar(input:FilingCalendarInput,context:RequestContext){const tenantId=this.tenant(context);try{assertFilingCalendarSource(input.source);}catch(error){this.reject(error,'FILING_CALENDAR_SOURCE_REJECTED');}const now=new Date(),contentHash=sha256(input),calendar:FilingCalendar={id:randomUUID(),name:input.name,versionTag:input.versionTag,jurisdictionCode:input.jurisdictionCode,year:input.year,source:{...input.source},contentHash,createdAt:now,createdBy:context.actorId,entries:input.entries.map(entry=>({id:randomUUID(),...entry}))};const result=await this.store.createCalendar({tenantId,calendar,traceId:context.traceId});if(!result.created&&result.calendar.contentHash!==contentHash)throw new ConflictException({code:'FILING_CALENDAR_VERSION_EXISTS',message:'Calendar version tag already exists with different content'});return result;}
  listCalendars(context:RequestContext){return this.store.listCalendars(this.tenant(context));}
  async createSop(input:FilingSopInput,context:RequestContext){const tenantId=this.tenant(context);try{assertFilingCalendarSource(input.source);}catch(error){this.reject(error,'FILING_SOP_SOURCE_REJECTED');}const now=new Date(),contentHash=sha256(input),sop:FilingSop={id:randomUUID(),name:input.name,versionTag:input.versionTag,jurisdictionCode:input.jurisdictionCode,source:{...input.source},steps:input.steps.map(step=>({...step})),contentHash,createdAt:now,createdBy:context.actorId};const result=await this.store.createSop({tenantId,sop,traceId:context.traceId});if(!result.created&&result.sop.contentHash!==contentHash)throw new ConflictException({code:'FILING_SOP_VERSION_EXISTS',message:'SOP version tag already exists with different content'});return result;}
  listSops(context:RequestContext){return this.store.listSops(this.tenant(context));}
  async generate(companyId:string,input:FilingTaskGenerationInput,context:RequestContext){const tenantId=await this.company(companyId,context),calendar=await this.store.findCalendar(tenantId,input.calendarId);if(!calendar)throw new NotFoundException('Filing calendar not found');if(input.usage==='production'&&calendar.source.type!=='official_notice')throw new ConflictException({code:'PRODUCTION_CALENDAR_SOURCE_REQUIRED',message:'Production tasks require a verified official filing calendar source'});const now=new Date(),tasks:FilingTask[]=calendar.entries.map(entry=>({id:randomUUID(),companyId,calendarId:calendar.id,calendarEntryId:entry.id,calendarName:calendar.name,calendarSourceType:calendar.source.type,taxType:entry.taxType,label:entry.label,periodStart:entry.periodStart,periodEnd:entry.periodEnd,dueDate:entry.dueDate,status:'todo',version:1,createdAt:now,createdBy:context.actorId,updatedAt:now,updatedBy:context.actorId}));const result=await this.store.generateTasks({tenantId,companyId,calendar,tasks,actorId:context.actorId,traceId:context.traceId,occurredAt:now});return{createdCount:result.createdCount,items:result.items.map(task=>this.withTiming(task,chinaDate(now)))};}
  async list(companyId:string,context:RequestContext,asOf?:string){const tenantId=await this.company(companyId,context);return(await this.store.listTasks(tenantId,companyId)).map(task=>this.withTiming(task,asOf??chinaDate(new Date())));}
  async todos(companyId:string,context:RequestContext,asOf?:string){return(await this.list(companyId,context,asOf)).filter(task=>task.status!=='paid');}
  async transition(companyId:string,id:string,input:FilingTaskTransitionInput,context:RequestContext){const tenantId=await this.company(companyId,context),current=await this.store.findTask(tenantId,companyId,id);if(!current)throw new NotFoundException('Filing task not found');if(current.version!==input.expectedVersion)throw new ConflictException({code:'FILING_TASK_CHANGED',message:'Filing task has changed'});let status;try{status=transitionFilingTask(current.status,input.action);}catch(error){return this.reject(error,'FILING_TASK_TRANSITION_REJECTED');}const changed=await this.store.transitionTask({tenantId,companyId,taskId:id,expectedVersion:input.expectedVersion,status,action:input.action,note:input.note,actorId:context.actorId,traceId:context.traceId,occurredAt:new Date()});if(!changed)throw new ConflictException({code:'FILING_TASK_CHANGED',message:'Filing task has changed'});return this.withTiming(changed,chinaDate(new Date()));}
  private withTiming(task:FilingTask,asOf:string){return{...task,timing:deriveFilingTaskTiming(task.status,task.dueDate,asOf)};}
  private async company(companyId:string,context:RequestContext){const tenantId=this.tenant(context);if(!await this.organizations.findCompany(tenantId,companyId))throw new NotFoundException('Company not found');return tenantId;}
  private tenant(context:RequestContext){if(!context.tenantId)throw new NotFoundException('Filing resource not found');return context.tenantId;}
  private reject(error:unknown,code:string):never{if(error instanceof FilingError)throw new ConflictException({code,message:error.message});throw error;}
}
function sha256(value:unknown){return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)]));return value;}
function chinaDate(value:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(value);}
