import{Inject,Injectable}from'@nestjs/common';
import{and,eq,sql}from'drizzle-orm';
import{Money}from'@ledgerly/domain';
import{randomUUID}from'node:crypto';
import{DATABASE,type Database}from'../../../infrastructure/database/database.provider.js';
import{auditEvents,businessEvents,invoiceSettlements,invoices,outboxEvents}from'../../../infrastructure/database/schema.js';
import type{SavedSettlement,SaveSettlementRecord,SettlementStore}from'../application/settlement-store.js';
@Injectable()
export class PostgresSettlementStore implements SettlementStore{
  constructor(@Inject(DATABASE)private readonly db:Database){}
  async save(record:SaveSettlementRecord):Promise<SavedSettlement|null>{const inserted=await this.db.transaction(async tx=>{await tx.execute(sql`select ${invoices.id} from ${invoices} where ${invoices.id}=${record.settlement.invoiceId} for update`);await tx.execute(sql`select ${businessEvents.id} from ${businessEvents} where ${businessEvents.id}=${record.settlement.paymentEventId} for update`);const invoiceAllocated=await this.sumInvoice(tx,record.tenantId,record.companyId,record.settlement.invoiceId),paymentAllocated=await this.sumPayment(tx,record.tenantId,record.companyId,record.settlement.paymentEventId);if(invoiceAllocated.add(record.settlement.amount).isGreaterThan(record.invoiceTotal)||paymentAllocated.add(record.settlement.amount).isGreaterThan(record.paymentTotal))return false;await tx.insert(invoiceSettlements).values({id:record.id,tenantId:record.tenantId,companyId:record.companyId,invoiceId:record.settlement.invoiceId,paymentEventId:record.settlement.paymentEventId,amount:record.settlement.amount.toString(),createdAt:record.createdAt,createdBy:record.actorId});await tx.insert(auditEvents).values({id:randomUUID(),tenantId:record.tenantId,actorId:record.actorId,action:'invoice.settlement.create',resourceType:'invoice_settlement',resourceId:record.id,outcome:'success',traceId:record.traceId,metadata:{invoiceId:record.settlement.invoiceId,paymentEventId:record.settlement.paymentEventId,amount:record.settlement.amount.toString()}});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId:record.tenantId,eventType:'invoice.settlement_created.v1',aggregateType:'invoice_settlement',aggregateId:record.id,payload:{settlementId:record.id,companyId:record.companyId,invoiceId:record.settlement.invoiceId,paymentEventId:record.settlement.paymentEventId},occurredAt:record.createdAt});return true});return inserted?{id:record.id,companyId:record.companyId,...record.settlement,createdAt:record.createdAt,createdBy:record.actorId}:null}
  async list(tenantId:string,companyId:string):Promise<readonly SavedSettlement[]>{const rows=await this.db.select().from(invoiceSettlements).where(and(eq(invoiceSettlements.tenantId,tenantId),eq(invoiceSettlements.companyId,companyId)));return rows.map(row=>({id:row.id,companyId:row.companyId,invoiceId:row.invoiceId,paymentEventId:row.paymentEventId,amount:Money.from(row.amount),createdAt:row.createdAt,createdBy:row.createdBy}))}
  async exists(tenantId:string,companyId:string,invoiceId:string,paymentEventId:string):Promise<boolean>{const[row]=await this.db.select({id:invoiceSettlements.id}).from(invoiceSettlements).where(and(eq(invoiceSettlements.tenantId,tenantId),eq(invoiceSettlements.companyId,companyId),eq(invoiceSettlements.invoiceId,invoiceId),eq(invoiceSettlements.paymentEventId,paymentEventId))).limit(1);return row!==undefined}
  allocatedForInvoice(tenantId:string,companyId:string,invoiceId:string):Promise<Money>{return this.sumInvoice(this.db,tenantId,companyId,invoiceId)}
  allocatedForPayment(tenantId:string,companyId:string,paymentEventId:string):Promise<Money>{return this.sumPayment(this.db,tenantId,companyId,paymentEventId)}
  private async sumInvoice(db:Pick<Database,'select'>,tenantId:string,companyId:string,invoiceId:string){const[row]=await db.select({total:sql<string>`coalesce(sum(${invoiceSettlements.amount}),0)`}).from(invoiceSettlements).where(and(eq(invoiceSettlements.tenantId,tenantId),eq(invoiceSettlements.companyId,companyId),eq(invoiceSettlements.invoiceId,invoiceId)));return Money.from(row?.total??'0')}
  private async sumPayment(db:Pick<Database,'select'>,tenantId:string,companyId:string,paymentEventId:string){const[row]=await db.select({total:sql<string>`coalesce(sum(${invoiceSettlements.amount}),0)`}).from(invoiceSettlements).where(and(eq(invoiceSettlements.tenantId,tenantId),eq(invoiceSettlements.companyId,companyId),eq(invoiceSettlements.paymentEventId,paymentEventId)));return Money.from(row?.total??'0')}
}
