import{Inject,Injectable}from'@nestjs/common';
import{and,asc,eq,or}from'drizzle-orm';
import type{FilingCalendarSource}from'@ledgerly/domain';
import{randomUUID}from'node:crypto';
import{DATABASE,type Database}from'../../../infrastructure/database/database.provider.js';
import{auditEvents,filingCalendarEntries,filingCalendars,filingTaskEvents,filingTasks,outboxEvents}from'../../../infrastructure/database/schema.js';
import type{CreateFilingCalendarRecord,FilingCalendar,FilingCalendarEntry,FilingStore,FilingTask,GenerateFilingTasksRecord,TransitionFilingTaskRecord}from'../application/filing-store.js';

@Injectable()
export class PostgresFilingStore implements FilingStore{
  constructor(@Inject(DATABASE)private readonly db:Database){}
  async createCalendar(record:CreateFilingCalendarRecord):Promise<{calendar:FilingCalendar;created:boolean}>{const inserted=await this.db.transaction(async tx=>{const[row]=await tx.insert(filingCalendars).values({id:record.calendar.id,tenantId:record.tenantId,name:record.calendar.name,versionTag:record.calendar.versionTag,jurisdictionCode:record.calendar.jurisdictionCode,year:record.calendar.year,sourceType:record.calendar.source.type,source:record.calendar.source,contentHash:record.calendar.contentHash,createdAt:record.calendar.createdAt,createdBy:record.calendar.createdBy}).onConflictDoNothing().returning();if(!row)return null;await tx.insert(filingCalendarEntries).values(record.calendar.entries.map(entry=>({...entry,calendarId:record.calendar.id})));await this.sideEffects(tx,record.tenantId,'filing_calendar',record.calendar.id,'filing_calendar.created',record.calendar.createdBy,record.traceId,record.calendar.createdAt,{versionTag:record.calendar.versionTag,sourceType:record.calendar.source.type});return row;});if(inserted)return{calendar:record.calendar,created:true};const[existing]=await this.db.select().from(filingCalendars).where(and(eq(filingCalendars.tenantId,record.tenantId),or(and(eq(filingCalendars.jurisdictionCode,record.calendar.jurisdictionCode),eq(filingCalendars.year,record.calendar.year),eq(filingCalendars.versionTag,record.calendar.versionTag)),eq(filingCalendars.contentHash,record.calendar.contentHash)))).limit(1);if(!existing)throw new Error('Filing calendar conflict');return{calendar:await this.hydrateCalendar(existing),created:false};}
  async listCalendars(tenantId:string){const rows=await this.db.select().from(filingCalendars).where(eq(filingCalendars.tenantId,tenantId)).orderBy(asc(filingCalendars.year),asc(filingCalendars.versionTag));return Promise.all(rows.map(row=>this.hydrateCalendar(row)));}
  async findCalendar(tenantId:string,id:string){const[row]=await this.db.select().from(filingCalendars).where(and(eq(filingCalendars.tenantId,tenantId),eq(filingCalendars.id,id))).limit(1);return row?this.hydrateCalendar(row):null;}
  async generateTasks(record:GenerateFilingTasksRecord):Promise<{items:readonly FilingTask[];createdCount:number}>{const created=await this.db.transaction(async tx=>{const rows=await tx.insert(filingTasks).values(record.tasks.map(task=>({id:task.id,tenantId:record.tenantId,companyId:record.companyId,calendarId:task.calendarId,calendarEntryId:task.calendarEntryId,status:task.status,version:task.version,createdAt:task.createdAt,createdBy:task.createdBy,updatedAt:task.updatedAt,updatedBy:task.updatedBy}))).onConflictDoNothing().returning();for(const task of rows){await tx.insert(filingTaskEvents).values({id:randomUUID(),filingTaskId:task.id,eventType:'generated',fromStatus:'todo',toStatus:'todo',note:`Generated from calendar ${record.calendar.versionTag}`,taskVersion:1,actedBy:record.actorId,actedAt:record.occurredAt});await this.sideEffects(tx,record.tenantId,'filing_task',task.id,'filing_task.generated',record.actorId,record.traceId,record.occurredAt,{companyId:record.companyId,calendarId:record.calendar.id,calendarEntryId:task.calendarEntryId});}return rows.length;});return{items:(await this.listTasks(record.tenantId,record.companyId)).filter(item=>item.calendarId===record.calendar.id),createdCount:created};}
  async listTasks(tenantId:string,companyId:string):Promise<readonly FilingTask[]>{const rows=await this.db.select({task:filingTasks,calendar:filingCalendars,entry:filingCalendarEntries}).from(filingTasks).innerJoin(filingCalendars,eq(filingTasks.calendarId,filingCalendars.id)).innerJoin(filingCalendarEntries,eq(filingTasks.calendarEntryId,filingCalendarEntries.id)).where(and(eq(filingTasks.tenantId,tenantId),eq(filingTasks.companyId,companyId))).orderBy(asc(filingCalendarEntries.dueDate));return rows.map(row=>this.presentTask(row.task,row.calendar,row.entry));}
  async findTask(tenantId:string,companyId:string,id:string):Promise<FilingTask|null>{const[row]=await this.db.select({task:filingTasks,calendar:filingCalendars,entry:filingCalendarEntries}).from(filingTasks).innerJoin(filingCalendars,eq(filingTasks.calendarId,filingCalendars.id)).innerJoin(filingCalendarEntries,eq(filingTasks.calendarEntryId,filingCalendarEntries.id)).where(and(eq(filingTasks.tenantId,tenantId),eq(filingTasks.companyId,companyId),eq(filingTasks.id,id))).limit(1);return row?this.presentTask(row.task,row.calendar,row.entry):null;}
  async transitionTask(record:TransitionFilingTaskRecord):Promise<FilingTask|null>{const updated=await this.db.transaction(async tx=>{const[current]=await tx.select().from(filingTasks).where(and(eq(filingTasks.id,record.taskId),eq(filingTasks.tenantId,record.tenantId),eq(filingTasks.companyId,record.companyId),eq(filingTasks.version,record.expectedVersion))).limit(1);if(!current)return null;const[row]=await tx.update(filingTasks).set({status:record.status,version:record.expectedVersion+1,...(record.status==='filed'?{filedAt:record.occurredAt,filedBy:record.actorId}:{}),...(record.status==='paid'?{paidAt:record.occurredAt,paidBy:record.actorId}:{}),updatedAt:record.occurredAt,updatedBy:record.actorId}).where(and(eq(filingTasks.id,record.taskId),eq(filingTasks.version,record.expectedVersion))).returning();if(!row)return null;await tx.insert(filingTaskEvents).values({id:randomUUID(),filingTaskId:record.taskId,eventType:record.action,fromStatus:current.status,toStatus:record.status,note:record.note,taskVersion:record.expectedVersion+1,actedBy:record.actorId,actedAt:record.occurredAt});await this.sideEffects(tx,record.tenantId,'filing_task',record.taskId,`filing_task.${record.action}`,record.actorId,record.traceId,record.occurredAt,{companyId:record.companyId,fromStatus:current.status,toStatus:record.status,version:record.expectedVersion+1});return row;});return updated?this.findTask(record.tenantId,record.companyId,record.taskId):null;}
  private async hydrateCalendar(row:typeof filingCalendars.$inferSelect):Promise<FilingCalendar>{const entries=await this.db.select().from(filingCalendarEntries).where(eq(filingCalendarEntries.calendarId,row.id)).orderBy(asc(filingCalendarEntries.dueDate));return{id:row.id,name:row.name,versionTag:row.versionTag,jurisdictionCode:row.jurisdictionCode,year:row.year,source:row.source as FilingCalendarSource,contentHash:row.contentHash,createdAt:row.createdAt,createdBy:row.createdBy,entries:entries.map(entry=>this.presentEntry(entry))};}
  private presentEntry(row:typeof filingCalendarEntries.$inferSelect):FilingCalendarEntry{return{id:row.id,taxType:row.taxType as FilingCalendarEntry['taxType'],label:row.label,periodStart:row.periodStart,periodEnd:row.periodEnd,dueDate:row.dueDate};}
  private presentTask(task:typeof filingTasks.$inferSelect,calendar:typeof filingCalendars.$inferSelect,entry:typeof filingCalendarEntries.$inferSelect):FilingTask{return{id:task.id,companyId:task.companyId,calendarId:task.calendarId,calendarEntryId:task.calendarEntryId,calendarName:calendar.name,calendarSourceType:calendar.sourceType as FilingTask['calendarSourceType'],taxType:entry.taxType as FilingTask['taxType'],label:entry.label,periodStart:entry.periodStart,periodEnd:entry.periodEnd,dueDate:entry.dueDate,status:task.status as FilingTask['status'],version:task.version,...(task.filedAt?{filedAt:task.filedAt}:{}),...(task.filedBy?{filedBy:task.filedBy}:{}),...(task.paidAt?{paidAt:task.paidAt}:{}),...(task.paidBy?{paidBy:task.paidBy}:{}),createdAt:task.createdAt,createdBy:task.createdBy,updatedAt:task.updatedAt,updatedBy:task.updatedBy};}
  private async sideEffects(tx:Parameters<Parameters<Database['transaction']>[0]>[0],tenantId:string,resourceType:string,resourceId:string,action:string,actorId:string,traceId:string,occurredAt:Date,metadata:Record<string,unknown>){await tx.insert(auditEvents).values({id:randomUUID(),tenantId,actorId,action,resourceType,resourceId,outcome:'success',traceId,metadata});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId,eventType:`${action}.v1`,aggregateType:resourceType,aggregateId:resourceId,payload:{resourceId,...metadata},occurredAt});}
}
