import{Injectable}from'@nestjs/common';
import type{CreateReviewCaseRecord,MutateReviewCaseRecord,ReviewCase,ReviewCaseFilters,ReviewCaseStore}from'../application/review-case-store.js';
@Injectable()
export class MemoryReviewCaseStore implements ReviewCaseStore{
  private readonly records=new Map<string,ReviewCase[]>();
  create(record:CreateReviewCaseRecord):Promise<{reviewCase:ReviewCase;created:boolean}>{const key=this.key(record.tenantId,record.companyId),items=this.records.get(key)??[],existing=items.find(item=>item.sourceType===record.sourceType&&item.sourceId===record.sourceId);if(existing)return Promise.resolve({reviewCase:existing,created:false});const reviewCase:Objectify<ReviewCase>={id:record.id,companyId:record.companyId,sourceType:record.sourceType,sourceId:record.sourceId,riskLevel:record.riskLevel,blocksFiling:record.blocksFiling,summary:record.summary,status:record.status,...(record.assignedTo?{assignedTo:record.assignedTo}:{}),version:1,createdAt:record.occurredAt,createdBy:record.actorId,updatedAt:record.occurredAt,updatedBy:record.actorId,items:[]};this.records.set(key,[reviewCase,...items]);return Promise.resolve({reviewCase,created:true});}
  list(tenantId:string,companyId:string,filters:ReviewCaseFilters):Promise<readonly ReviewCase[]>{return Promise.resolve((this.records.get(this.key(tenantId,companyId))??[]).filter(item=>(!filters.status||item.status===filters.status)&&(!filters.riskLevel||item.riskLevel===filters.riskLevel)&&(!filters.assignedTo||item.assignedTo===filters.assignedTo)));}
  find(tenantId:string,companyId:string,id:string):Promise<ReviewCase|null>{return Promise.resolve((this.records.get(this.key(tenantId,companyId))??[]).find(item=>item.id===id)??null);}
  mutate(record:MutateReviewCaseRecord):Promise<ReviewCase|null>{const key=this.key(record.tenantId,record.companyId),items=this.records.get(key)??[],index=items.findIndex(item=>item.id===record.reviewCaseId&&item.version===record.expectedVersion);if(index<0)return Promise.resolve(null);const current=items[index]!;const workItem=record.workItem?{...record.workItem,documentIds:[...record.workItem.documentIds],createdAt:record.occurredAt,createdBy:record.actorId}:undefined;const changed:ReviewCase={...current,status:record.status,...(record.assignedTo?{assignedTo:record.assignedTo}:{}),version:current.version+1,updatedAt:record.occurredAt,updatedBy:record.actorId,items:workItem?[...current.items,workItem]:current.items};this.records.set(key,items.map((item,i)=>i===index?changed:item));return Promise.resolve(changed);}
  private key(tenantId:string,companyId:string){return`${tenantId}:${companyId}`;}
}
type Objectify<T>={-readonly[P in keyof T]:T[P]};
