import{Inject,Injectable}from'@nestjs/common';
import{and,desc,eq}from'drizzle-orm';
import{randomUUID}from'node:crypto';
import{DATABASE,type Database}from'../../../infrastructure/database/database.provider.js';
import{auditEvents,outboxEvents,reviewCaseEvents,reviewCases,reviewCaseWorkItems}from'../../../infrastructure/database/schema.js';
import type{CreateReviewCaseRecord,MutateReviewCaseRecord,ReviewCase,ReviewCaseFilters,ReviewCaseStore,ReviewWorkItem}from'../application/review-case-store.js';
@Injectable()
export class PostgresReviewCaseStore implements ReviewCaseStore{
  constructor(@Inject(DATABASE)private readonly db:Database){}
  async create(record:CreateReviewCaseRecord):Promise<{reviewCase:ReviewCase;created:boolean}>{const created=await this.db.transaction(async tx=>{const[inserted]=await tx.insert(reviewCases).values({id:record.id,tenantId:record.tenantId,companyId:record.companyId,sourceType:record.sourceType,sourceId:record.sourceId,riskLevel:record.riskLevel,blocksFiling:record.blocksFiling,summary:record.summary,status:record.status,...(record.assignedTo?{assignedTo:record.assignedTo}:{}),createdAt:record.occurredAt,createdBy:record.actorId,updatedAt:record.occurredAt,updatedBy:record.actorId}).onConflictDoNothing().returning();if(!inserted)return null;await tx.insert(reviewCaseEvents).values({id:randomUUID(),reviewCaseId:record.id,eventType:'created',fromStatus:'open',toStatus:record.status,note:record.summary,caseVersion:1,actedBy:record.actorId,actedAt:record.occurredAt});await this.writeSideEffects(tx,record.tenantId,record.id,record.companyId,'created',record.actorId,record.traceId,record.occurredAt,{sourceType:record.sourceType,sourceId:record.sourceId});return inserted;});if(created)return{reviewCase:{...this.present(created),items:[]},created:true};const[existing]=await this.db.select().from(reviewCases).where(and(eq(reviewCases.tenantId,record.tenantId),eq(reviewCases.companyId,record.companyId),eq(reviewCases.sourceType,record.sourceType),eq(reviewCases.sourceId,record.sourceId))).limit(1);if(!existing)throw new Error('Review case conflict');return{reviewCase:await this.hydrate(existing),created:false};}
  async list(tenantId:string,companyId:string,filters:ReviewCaseFilters):Promise<readonly ReviewCase[]>{const conditions=[eq(reviewCases.tenantId,tenantId),eq(reviewCases.companyId,companyId)];if(filters.status)conditions.push(eq(reviewCases.status,filters.status));if(filters.riskLevel)conditions.push(eq(reviewCases.riskLevel,filters.riskLevel));if(filters.assignedTo)conditions.push(eq(reviewCases.assignedTo,filters.assignedTo));const rows=await this.db.select().from(reviewCases).where(and(...conditions)).orderBy(desc(reviewCases.updatedAt));return Promise.all(rows.map(row=>this.hydrate(row)));}
  async find(tenantId:string,companyId:string,id:string):Promise<ReviewCase|null>{const[row]=await this.db.select().from(reviewCases).where(and(eq(reviewCases.tenantId,tenantId),eq(reviewCases.companyId,companyId),eq(reviewCases.id,id))).limit(1);return row?this.hydrate(row):null;}
  async mutate(record:MutateReviewCaseRecord):Promise<ReviewCase|null>{const row=await this.db.transaction(async tx=>{const[current]=await tx.select().from(reviewCases).where(and(eq(reviewCases.id,record.reviewCaseId),eq(reviewCases.tenantId,record.tenantId),eq(reviewCases.companyId,record.companyId),eq(reviewCases.version,record.expectedVersion))).limit(1);if(!current)return null;const[updated]=await tx.update(reviewCases).set({status:record.status,...(record.assignedTo?{assignedTo:record.assignedTo}:{}),version:record.expectedVersion+1,updatedAt:record.occurredAt,updatedBy:record.actorId}).where(and(eq(reviewCases.id,record.reviewCaseId),eq(reviewCases.version,record.expectedVersion))).returning();if(!updated)return null;if(record.workItem)await tx.insert(reviewCaseWorkItems).values({id:record.workItem.id,reviewCaseId:record.reviewCaseId,kind:record.workItem.kind,content:record.workItem.content,documentIds:record.workItem.documentIds,createdAt:record.occurredAt,createdBy:record.actorId});await tx.insert(reviewCaseEvents).values({id:randomUUID(),reviewCaseId:record.reviewCaseId,eventType:record.action,fromStatus:current.status,toStatus:record.status,note:record.note,caseVersion:record.expectedVersion+1,actedBy:record.actorId,actedAt:record.occurredAt});await this.writeSideEffects(tx,record.tenantId,record.reviewCaseId,record.companyId,record.action,record.actorId,record.traceId,record.occurredAt,{fromStatus:current.status,toStatus:record.status,version:record.expectedVersion+1});return updated;});return row?this.hydrate(row):null;}
  private async hydrate(row:typeof reviewCases.$inferSelect):Promise<ReviewCase>{const items=await this.db.select().from(reviewCaseWorkItems).where(eq(reviewCaseWorkItems.reviewCaseId,row.id)).orderBy(reviewCaseWorkItems.createdAt);return{...this.present(row),items:items.map(item=>this.presentItem(item))};}
  private present(row:typeof reviewCases.$inferSelect):Omit<ReviewCase,'items'>{return{id:row.id,companyId:row.companyId,sourceType:row.sourceType as ReviewCase['sourceType'],sourceId:row.sourceId,riskLevel:row.riskLevel as ReviewCase['riskLevel'],blocksFiling:row.blocksFiling,summary:row.summary,status:row.status as ReviewCase['status'],...(row.assignedTo?{assignedTo:row.assignedTo}:{}),version:row.version,createdAt:row.createdAt,createdBy:row.createdBy,updatedAt:row.updatedAt,updatedBy:row.updatedBy};}
  private presentItem(row:typeof reviewCaseWorkItems.$inferSelect):ReviewWorkItem{return{id:row.id,kind:row.kind as ReviewWorkItem['kind'],content:row.content,documentIds:row.documentIds as string[],createdAt:row.createdAt,createdBy:row.createdBy};}
  private async writeSideEffects(tx:Parameters<Parameters<Database['transaction']>[0]>[0],tenantId:string,id:string,companyId:string,action:string,actorId:string,traceId:string,occurredAt:Date,metadata:Record<string,unknown>){await tx.insert(auditEvents).values({id:randomUUID(),tenantId,actorId,action:`review_case.${action}`,resourceType:'review_case',resourceId:id,outcome:'success',traceId,metadata});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId,eventType:`review_case.${action}.v1`,aggregateType:'review_case',aggregateId:id,payload:{reviewCaseId:id,companyId,...metadata},occurredAt});}
}
