'use client';

import { apiFetch } from '@/app/lib/api-fetch';

import {
  businessEventListResponseSchema, documentContentResponseSchema, documentListResponseSchema,
  documentResponseSchema, documentUploadResponseSchema,
  type BusinessEventResponse, type DocumentResponse,
} from '@ledgerly/contracts';
import { useEffect, useMemo, useState, type FormEvent } from 'react';

interface WorkspaceContext { tenantId:string; companyId:string }
const typeLabels={invoice:'发票',bank_receipt:'银行回单',contract:'合同',screenshot:'截图',payroll:'工资表',other:'其他'} as const;

function readContext():WorkspaceContext|null { try{const raw:unknown=JSON.parse(window.localStorage.getItem('ledgerly.context')??'null');if(typeof raw!=='object'||raw===null)return null;const value=raw as Partial<WorkspaceContext>;return typeof value.tenantId==='string'&&typeof value.companyId==='string'?{tenantId:value.tenantId,companyId:value.companyId}:null;}catch{return null;} }
function api(){return process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';}
function headers(workspace:WorkspaceContext,json=false){return {'x-user-id':'10000000-0000-4000-8000-000000000001','x-tenant-id':workspace.tenantId,...(json?{'content-type':'application/json'}:{})};}

async function encodeFile(file:File):Promise<string>{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';const size=0x8000;for(let start=0;start<bytes.length;start+=size)binary+=String.fromCharCode(...bytes.subarray(start,start+size));return btoa(binary);}
function mediaType(file:File){if(file.type)return file.type;const extension=file.name.toLowerCase().split('.').pop();return extension==='ofd'?'application/ofd':extension==='pdf'?'application/pdf':extension==='png'?'image/png':extension==='jpg'||extension==='jpeg'?'image/jpeg':'';}

export function DocumentManager(){
  const [workspace,setWorkspace]=useState<WorkspaceContext|null>(null);const [ready,setReady]=useState(false);
  const [documents,setDocuments]=useState<DocumentResponse[]>([]);const [events,setEvents]=useState<BusinessEventResponse[]>([]);
  const [message,setMessage]=useState<string|null>(null);const [pending,setPending]=useState(false);
  const eventNames=useMemo(()=>new Map(events.map(item=>[item.id,`${item.occurredOn} · ${item.description} · ¥${item.amount}`])),[events]);

  useEffect(()=>{const current=readContext();setWorkspace(current);if(!current){setReady(true);return;}void Promise.all([
    apiFetch(`${api()}/v1/companies/${current.companyId}/documents`,{headers:headers(current)}).then(r=>r.json()),
    apiFetch(`${api()}/v1/companies/${current.companyId}/business-events`,{headers:headers(current)}).then(r=>r.json()),
  ]).then(([docsPayload,eventsPayload]:unknown[])=>{const docs=documentListResponseSchema.safeParse(docsPayload);const facts=businessEventListResponseSchema.safeParse(eventsPayload);if(docs.success)setDocuments(docs.data.items);if(facts.success)setEvents(facts.data.items);}).catch(()=>setMessage('暂时无法读取档案。')).finally(()=>setReady(true));},[]);

  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!workspace)return;const formElement=event.currentTarget;const form=new FormData(formElement);const file=form.get('file');if(!(file instanceof File)||file.size===0)return setMessage('请选择文件。');if(file.size>5_000_000)return setMessage('文件不能超过 5 MB。');setPending(true);setMessage('正在计算哈希并进行安全检查…');try{const response=await apiFetch(`${api()}/v1/companies/${workspace.companyId}/documents`,{method:'POST',headers:headers(workspace,true),body:JSON.stringify({type:form.get('type'),title:form.get('title'),accountingMonth:form.get('accountingMonth'),fileName:file.name,mediaType:mediaType(file),contentBase64:await encodeFile(file)})});const payload:unknown=await response.json();if(!response.ok)throw new Error(response.status===400?'文件格式、大小或安全扫描未通过。':'上传失败。');const result=documentUploadResponseSchema.parse(payload);setDocuments(current=>result.duplicate?current:[result.document,...current]);setMessage(result.duplicate?'检测到相同文件，已返回现有档案，没有重复保存。':'单据已安全归档。');if(!result.duplicate)formElement.reset();}catch(error:unknown){setMessage(error instanceof Error?error.message:'上传失败。');}finally{setPending(false);}}

  async function addVersion(document:DocumentResponse,file:File){if(!workspace||file.size===0)return;if(file.size>5_000_000)return setMessage('文件不能超过 5 MB。');setPending(true);setMessage('正在保存新版本…');try{const response=await apiFetch(`${api()}/v1/companies/${workspace.companyId}/documents/${document.id}/versions`,{method:'POST',headers:headers(workspace,true),body:JSON.stringify({fileName:file.name,mediaType:mediaType(file),contentBase64:await encodeFile(file)})});const payload:unknown=await response.json();if(!response.ok)throw new Error('新版本保存失败或文件已归档到其他档案。');const result=documentUploadResponseSchema.parse(payload);setDocuments(current=>current.map(item=>item.id===result.document.id?result.document:item));setMessage(result.duplicate?'该文件就是已有版本，没有重复保存。':'新版本已归档，旧版本仍然保留。');}catch(error:unknown){setMessage(error instanceof Error?error.message:'版本保存失败。');}finally{setPending(false);}}

  async function link(document:DocumentResponse,eventId:string){if(!workspace||!eventId)return;setPending(true);setMessage('正在建立证据关联…');try{const response=await apiFetch(`${api()}/v1/companies/${workspace.companyId}/documents/${document.id}/links/business-events/${eventId}`,{method:'POST',headers:headers(workspace,true),body:'{}'});const payload:unknown=await response.json();if(!response.ok)throw new Error('关联失败。');const saved=documentResponseSchema.parse(payload);setDocuments(current=>current.map(item=>item.id===saved.id?saved:item));setMessage('单据已关联到业务事项。');}catch(error:unknown){setMessage(error instanceof Error?error.message:'关联失败。');}finally{setPending(false);}}

  async function download(document:DocumentResponse){if(!workspace)return;const version=document.versions.at(-1);if(!version)return;setPending(true);try{const response=await apiFetch(`${api()}/v1/companies/${workspace.companyId}/documents/${document.id}/versions/${version.id}/content`,{headers:headers(workspace)});const payload:unknown=await response.json();if(!response.ok)throw new Error('读取文件失败。');const content=documentContentResponseSchema.parse(payload);const binary=atob(content.contentBase64);const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:content.mediaType}));const anchor=window.document.createElement('a');anchor.href=url;anchor.download=content.fileName;anchor.click();URL.revokeObjectURL(url);setMessage('已下载当前版本。');}catch(error:unknown){setMessage(error instanceof Error?error.message:'下载失败。');}finally{setPending(false);}}

  if(!ready)return <section className="document-workspace"><div className="onboarding-card">正在读取档案…</div></section>;
  if(!workspace)return <section className="document-workspace"><div className="onboarding-card">请先完成企业建档和账套初始化。</div></section>;
  return <section className="document-workspace"><form className="onboarding-card document-upload" onSubmit={e=>void upload(e)}><h2>归档新单据</h2><label>档案类型<select name="type" defaultValue="contract"><option value="invoice">发票</option><option value="bank_receipt">银行回单</option><option value="contract">合同</option><option value="screenshot">截图</option><option value="payroll">工资表</option><option value="other">其他</option></select></label><label>档案标题<input name="title" required maxLength={200} placeholder="例如：十月技术服务合同"/></label><label>所属月份<input name="accountingMonth" type="month" defaultValue="2026-10" required/></label><label>文件<input name="file" type="file" accept=".pdf,.ofd,.jpg,.jpeg,.png,application/pdf,application/ofd,image/jpeg,image/png" required/><small>支持 PDF、OFD、JPG、PNG，最大 5 MB。</small></label><button className="primary button" disabled={pending}>上传并归档</button>{message&&<p className={message.includes('失败')||message.includes('不能')||message.includes('未通过')?'form-error':'form-success'} role="status">{message}</p>}</form><section className="document-list"><div className="list-title"><div><p className="eyebrow">共 {documents.length} 份</p><h2>单据档案</h2></div><span>原文件仅通过鉴权接口读取</span></div>{documents.length===0?<div className="empty-state">还没有单据档案。</div>:documents.map(item=><article key={item.id}><header><span>{typeLabels[item.type]}</span><div><strong>{item.title}</strong><small>{item.accountingMonth} · 当前 V{item.currentVersion} · {item.versions.at(-1)?.fileName}</small></div><button className="secondary" disabled={pending} onClick={()=>void download(item)}>下载</button></header><div className="document-version-row"><label>增加新版本<input type="file" accept=".pdf,.ofd,.jpg,.jpeg,.png,application/pdf,application/ofd,image/jpeg,image/png" disabled={pending} onChange={e=>{const file=e.target.files?.[0];if(file)void addVersion(item,file);e.target.value='';}}/></label><span>{item.versions.length} 个版本 · 最新文件 {formatBytes(item.versions.at(-1)?.byteSize??0)}</span></div><div className="evidence-row"><select defaultValue="" disabled={pending||events.length===0} onChange={e=>{if(e.target.value)void link(item,e.target.value);e.target.value='';}}><option value="">关联到业务事项…</option>{events.filter(event=>!item.linkedBusinessEventIds.includes(event.id)).map(event=><option key={event.id} value={event.id}>{eventNames.get(event.id)}</option>)}</select><div>{item.linkedBusinessEventIds.length===0?<small>尚未关联业务事项</small>:item.linkedBusinessEventIds.map(id=><span key={id}>{eventNames.get(id)??id}</span>)}</div></div></article>)}</section></section>;
}

function formatBytes(value:number){return value<1024?`${value} B`:`${(value/1024).toFixed(1)} KB`;}
