import{ConflictException,Inject,Injectable,NotFoundException}from'@nestjs/common';
import type{ReviewCaseAssignment,ReviewCaseDecisionInput,ReviewCaseInput,ReviewCaseTransition,ReviewWorkItemInput}from'@ledgerly/contracts';
import{assertReviewWorkItemAllowed,assignReviewCase,decideReviewCase,ReviewCaseError,transitionReviewCase,type ReviewCaseStatus}from'@ledgerly/domain';
import{randomUUID}from'node:crypto';
import type{RequestContext}from'../../organization/application/organization.service.js';
import{REVIEW_CASE_STORE,type ReviewCase,type ReviewCaseFilters,type ReviewCaseStore}from'./review-case-store.js';
import{REVIEW_SOURCE_RESOLVER,type ReviewSourceResolver}from'./review-source-resolver.js';

@Injectable()
export class ReviewCaseService{
  constructor(@Inject(REVIEW_CASE_STORE)private readonly store:ReviewCaseStore,@Inject(REVIEW_SOURCE_RESOLVER)private readonly sources:ReviewSourceResolver){}
  async create(companyId:string,input:ReviewCaseInput,context:RequestContext){const tenantId=this.tenant(context),source=await this.sources.resolve(tenantId,companyId,input.sourceType,input.sourceId);if(!source)throw new NotFoundException('Review source not found');let status:ReviewCaseStatus='open';if(input.assignedTo)status=assignReviewCase({status,createdBy:source.createdBy},input.assignedTo);const{createdBy,...facts}=source;return this.store.create({id:randomUUID(),tenantId,companyId,...input,...facts,status,actorId:createdBy,traceId:context.traceId,occurredAt:new Date()});}
  list(companyId:string,filters:ReviewCaseFilters,context:RequestContext){return this.store.list(this.tenant(context),companyId,filters);}
  async get(companyId:string,id:string,context:RequestContext){const item=await this.store.find(this.tenant(context),companyId,id);if(!item)throw new NotFoundException('Review case not found');return item;}
  async assign(companyId:string,id:string,input:ReviewCaseAssignment,context:RequestContext){const current=await this.current(companyId,id,input.expectedVersion,context);if(current.assignedTo&&current.assignedTo!==context.actorId)throw new ConflictException({code:'REVIEW_CASE_ASSIGNMENT_REJECTED',message:'Only the assigned reviewer can transfer this case'});return this.change(current,input.expectedVersion,assignReviewCase(current,input.assignedTo),context,'assigned',input.note,input.assignedTo);}
  async appendWorkItem(companyId:string,id:string,input:ReviewWorkItemInput,context:RequestContext){const tenantId=this.tenant(context),current=await this.current(companyId,id,input.expectedVersion,context);try{assertReviewWorkItemAllowed(current,context.actorId);}catch(error){this.reject(error);}if(!await this.sources.documentsExist(tenantId,companyId,input.documentIds))throw new NotFoundException('Review document not found');const status=input.kind==='document_request'?transitionReviewCase(current,context.actorId,'request_documents'):current.status;return this.change(current,input.expectedVersion,status,context,`work_item.${input.kind}`,input.content,current.assignedTo,{id:randomUUID(),kind:input.kind,content:input.content,documentIds:input.documentIds});}
  async transition(companyId:string,id:string,input:ReviewCaseTransition,context:RequestContext){const current=await this.current(companyId,id,input.expectedVersion,context);let status:ReviewCaseStatus;try{status=transitionReviewCase(current,context.actorId,input.action);}catch(error){return this.reject(error);}return this.change(current,input.expectedVersion,status,context,input.action,input.note,current.assignedTo);}
  async decide(companyId:string,id:string,input:ReviewCaseDecisionInput,context:RequestContext){const current=await this.current(companyId,id,input.expectedVersion,context);let status:ReviewCaseStatus;try{status=decideReviewCase(current,context.actorId,input.decision);}catch(error){return this.reject(error);}return this.change(current,input.expectedVersion,status,context,`decision.${input.decision}`,input.reason,current.assignedTo);}
  private async current(companyId:string,id:string,expectedVersion:number,context:RequestContext){const current=await this.get(companyId,id,context);if(current.version!==expectedVersion)throw new ConflictException({code:'REVIEW_CASE_CHANGED',message:'Review case has changed'});return current;}
  private async change(current:ReviewCase,expectedVersion:number,status:ReviewCaseStatus,context:RequestContext,action:string,note:string,assignedTo?:string,workItem?:Parameters<ReviewCaseStore['mutate']>[0]['workItem']){const changed=await this.store.mutate({tenantId:this.tenant(context),companyId:current.companyId,reviewCaseId:current.id,expectedVersion,status,...(assignedTo?{assignedTo}:{}),action,note:note.trim(),actorId:context.actorId,traceId:context.traceId,occurredAt:new Date(),...(workItem?{workItem}:{})});if(!changed)throw new ConflictException({code:'REVIEW_CASE_CHANGED',message:'Review case has changed'});return changed;}
  private tenant(context:RequestContext){if(!context.tenantId)throw new NotFoundException('Review case not found');return context.tenantId;}
  private reject(error:unknown):never{if(error instanceof ReviewCaseError)throw new ConflictException({code:'REVIEW_CASE_ACTION_REJECTED',message:error.message});throw error;}
}
