import { describe,expect,it } from 'vitest';
import { OrganizationService } from '../src/modules/organization/application/organization.service.js';
import { MemoryOrganizationStore } from '../src/modules/organization/infrastructure/memory-organization.store.js';
import { ProfileScopeService } from '../src/modules/profile-scope/application/profile-scope.service.js';
import { MemoryScopeStore } from '../src/modules/profile-scope/infrastructure/memory-scope.store.js';
import { LedgerSetupService } from '../src/modules/ledger-setup/application/ledger-setup.service.js';
import { MemoryLedgerSetupStore } from '../src/modules/ledger-setup/infrastructure/memory-ledger-setup.store.js';
import { CounterpartyService } from '../src/modules/counterparty/application/counterparty.service.js';
import { MemoryCounterpartyStore } from '../src/modules/counterparty/infrastructure/memory-counterparty.store.js';
import { BusinessEventService } from '../src/modules/business-event/application/business-event.service.js';
import { MemoryBusinessEventStore } from '../src/modules/business-event/infrastructure/memory-business-event.store.js';
import { AccountingService } from '../src/modules/accounting/application/accounting.service.js';
import { MemoryVoucherStore } from '../src/modules/accounting/infrastructure/memory-voucher.store.js';
import { MemorySettlementStore } from '../src/modules/reconciliation/infrastructure/memory-settlement.store.js';
import { financialReportsResponseSchema } from '@ledgerly/contracts';

const actorId='10000000-0000-4000-8000-000000000001';
async function fixture(openingBalance='0.00',openingBalanceSource:'none'|'paid_in_capital'|'shareholder_advance'='none'){const organizations=new MemoryOrganizationStore(),scopes=new MemoryScopeStore(),setups=new MemoryLedgerSetupStore(),parties=new MemoryCounterpartyStore(),events=new MemoryBusinessEventStore();const created=await new OrganizationService(organizations).bootstrap({tenantName:'测试',company:{name:'常州市测试科技有限公司',unifiedSocialCreditCode:'913204001234567890',provinceCode:'32',cityCode:'3204'}},{actorId,traceId:'create'});const context={actorId,tenantId:created.tenantId,traceId:'test'};await new ProfileScopeService(organizations,scopes).evaluate(created.company.id,{entityType:'one_person_llc',vatTaxpayerStatus:'small_scale',vatFilingCycle:'quarterly',incomeTaxCollection:'audit',industry:'modern_service',hasInventory:false,hasBranches:false,hasImportExport:false,hasForeignCurrency:false,hasSpecialVatFivePercent:false,hasDifferenceTax:false,hasCrossRegionPrepayment:false,hasComplexPayroll:false,hasShareholderTransactions:false,hasComplexTaxAdjustments:false,sourceDocumentsComplete:true},context);await new LedgerSetupService(organizations,scopes,setups).create(created.company.id,{accountName:'基本户',accountType:'bank',bankName:'招商银行',accountNumberLast4:'1234',openingBalance,openingBalanceSource,openingBalanceAsOf:'2026-09-30',periodStart:'2026-10-01',periodEnd:'2026-10-31'},context);const party=await new CounterpartyService(organizations,setups,parties).create(created.company.id,{name:'示例客户',type:'customer'},context);return{created,context,party,eventService:new BusinessEventService(setups,parties,events),service:new AccountingService(setups,events,new MemoryVoucherStore(),new MemorySettlementStore())};}

describe('AccountingService',()=>{
  it('generates a balanced service voucher and is idempotent',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'service_completed',occurredOn:'2026-10-08',amount:'1060.00',counterpartyId:party.id,description:'完成技术服务'},context);const event=await eventService.confirm(created.company.id,draft.id,context);const first=await service.generate(created.company.id,event.id,context);const second=await service.generate(created.company.id,event.id,context);expect(first.generated).toBe(true);expect(second.generated).toBe(false);expect(second.voucher.id).toBe(first.voucher.id);expect(first.voucher.entries.map(item=>[item.side,item.accountCode,item.amount.toString()])).toEqual([['debit','1122','1060.00'],['credit','5001','1060.00']]);});
  it('rejects a draft source event',async()=>{const{created,context,party,eventService,service}=await fixture();const event=await eventService.create(created.company.id,{type:'money_received',occurredOn:'2026-10-08',amount:'100.00',counterpartyId:party.id,description:'草稿'},context);await expect(service.generate(created.company.id,event.id,context)).rejects.toMatchObject({status:409});});
  it('routes invoice events to review instead of treating invoices as revenue',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'invoice_issued',occurredOn:'2026-10-08',amount:'100.00',counterpartyId:party.id,description:'仅开票'},context);const event=await eventService.confirm(created.company.id,draft.id,context);await expect(service.generate(created.company.id,event.id,context)).rejects.toMatchObject({status:409,response:{code:'VOUCHER_MAPPING_REQUIRES_REVIEW'}});});
  it('builds strict financial reports from confirmed vouchers and excludes drafts',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'service_completed',occurredOn:'2026-10-08',amount:'1060.00',counterpartyId:party.id,description:'报表服务收入'},context);const event=await eventService.confirm(created.company.id,draft.id,context);const generated=await service.generate(created.company.id,event.id,context);const before=financialReportsResponseSchema.parse(await service.reports(created.company.id,context));expect(before.profitStatement.profit).toBe('0.00');expect(before.basis.includesDraftVouchers).toBe(false);await service.confirm(created.company.id,generated.voucher.id,1,context);const after=financialReportsResponseSchema.parse(await service.reports(created.company.id,context));expect(after.profitStatement).toMatchObject({totalRevenue:'1060.00',totalExpenses:'0.00',profit:'1060.00'});expect(after.balanceSheet).toMatchObject({totalAssets:'1060.00',totalLiabilities:'0.00',totalEquity:'1060.00',difference:'0.00',balanced:true});});
  it('rejects events outside the initialized period',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'money_received',occurredOn:'2026-11-01',amount:'100.00',counterpartyId:party.id,description:'跨期收款'},context);const event=await eventService.confirm(created.company.id,draft.id,context);await expect(service.generate(created.company.id,event.id,context)).rejects.toMatchObject({status:409,response:{code:'EVENT_OUTSIDE_OPEN_PERIOD'}});});
  it('confirms, posts and reverses a voucher without losing the audit chain',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'service_completed',occurredOn:'2026-10-08',amount:'1060.00',counterpartyId:party.id,description:'待冲销服务'},context);const event=await eventService.confirm(created.company.id,draft.id,context);const generated=await service.generate(created.company.id,event.id,context);const confirmed=await service.confirm(created.company.id,generated.voucher.id,1,context);expect(confirmed.status).toBe('confirmed');const before=await service.ledger(created.company.id,context);expect(before.trialBalance.find(item=>item.accountCode==='1122')?.endingDebit).toBe('1060.00');const reversal=await service.reverse(created.company.id,confirmed.id,{reversalDate:'2026-10-09',reason:'重复记录',expectedVersion:2},context);expect(reversal.reversalOfVoucherId).toBe(confirmed.id);const after=await service.ledger(created.company.id,context),receivable=after.trialBalance.find(item=>item.accountCode==='1122');expect(receivable).toMatchObject({debitMovement:'1060.00',creditMovement:'1060.00',endingDebit:'0.00',endingCredit:'0.00'});expect((await service.list(created.company.id,context)).find(item=>item.id===confirmed.id)?.status).toBe('reversed');const reports=await service.reports(created.company.id,context);expect(reports.profitStatement.profit).toBe('0.00');expect(reports.balanceSheet).toMatchObject({totalAssets:'0.00',totalEquity:'0.00',difference:'0.00',balanced:true});});
  it('blocks period locking while drafts exist and blocks writes after locking',async()=>{const{created,context,party,eventService,service}=await fixture();const draft=await eventService.create(created.company.id,{type:'service_completed',occurredOn:'2026-10-08',amount:'100.00',counterpartyId:party.id,description:'锁账测试'},context);const event=await eventService.confirm(created.company.id,draft.id,context);const generated=await service.generate(created.company.id,event.id,context);await expect(service.lockPeriod(created.company.id,context)).rejects.toMatchObject({response:{code:'DRAFT_VOUCHERS_EXIST'}});await service.confirm(created.company.id,generated.voucher.id,1,context);const locked=await service.lockPeriod(created.company.id,context);expect(locked.periodStatus).toBe('locked');await expect(service.reverse(created.company.id,generated.voucher.id,{reversalDate:'2026-10-09',reason:'不应成功',expectedVersion:2},context)).rejects.toMatchObject({response:{code:'ACCOUNTING_PERIOD_LOCKED'}});});
  it('includes a balanced opening entry in the trial balance and reports',async()=>{const{created,context,service}=await fixture('5000.00','paid_in_capital');const ledger=await service.ledger(created.company.id,context);expect(ledger.openingBalance.includedInTrialBalance).toBe(true);expect(ledger.trialBalance).toEqual(expect.arrayContaining([expect.objectContaining({accountCode:'1002',openingDebit:'5000.00',endingDebit:'5000.00'}),expect.objectContaining({accountCode:'3001',openingCredit:'5000.00',endingCredit:'5000.00'})]));const reports=await service.reports(created.company.id,context);expect(reports.balanceSheet).toMatchObject({totalAssets:'5000.00',totalLiabilities:'0.00',totalEquity:'5000.00',difference:'0.00',balanced:true});});
});
