import{describe,expect,it}from'vitest';
import type{OrganizationStore}from'../src/modules/organization/application/organization-store.js';
import{FilingService}from'../src/modules/filing/application/filing.service.js';
import{MemoryFilingStore}from'../src/modules/filing/infrastructure/memory-filing.store.js';

const actorId='10000000-0000-4000-8000-000000000001',tenantId='20000000-0000-4000-8000-000000000002',companyId='30000000-0000-4000-8000-000000000003';
const context={actorId,tenantId,traceId:'filing-test'};
const organizations:OrganizationStore={bootstrap:()=>Promise.resolve(),findCompany:(tenant,company)=>Promise.resolve(tenant===tenantId&&company===companyId?{id:companyId,tenantId,name:'测试企业',unifiedSocialCreditCode:'913200001234567890',provinceCode:'32',cityCode:'3201',status:'draft',version:1,createdAt:new Date(),createdBy:actorId} as never:null),recordDeniedCompanyAccess:()=>Promise.resolve()};
const input={name:'R2 测试征期日历',versionTag:'r2-fixture-1',jurisdictionCode:'CN-JS',year:2026,source:{type:'test_fixture' as const,title:'仅用于 R2 流程演示'},entries:[{taxType:'vat' as const,label:'增值税测试申报',periodStart:'2026-09-01',periodEnd:'2026-09-30',dueDate:'2026-10-09'}]};
const sopInput={name:'R3 测试申报 SOP',versionTag:'r3-fixture-1',jurisdictionCode:'CN-JS',source:{type:'test_fixture' as const,title:'仅用于 R3 冻结流程演示'},steps:[{code:'prepare','title':'准备资料','instruction':'核对申报任务、计算引用和已批准复核记录'}]};

describe('FilingService',()=>{
  it('creates a versioned calendar and generates company tasks idempotently',async()=>{const service=new FilingService(new MemoryFilingStore(),organizations);const calendar=await service.createCalendar(input,context),same=await service.createCalendar(input,context);expect(calendar.created).toBe(true);expect(same).toMatchObject({created:false,calendar:{id:calendar.calendar.id}});const first=await service.generate(companyId,{calendarId:calendar.calendar.id,usage:'test'},context),second=await service.generate(companyId,{calendarId:calendar.calendar.id,usage:'test'},context);expect(first).toMatchObject({createdCount:1,items:[{status:'todo'}]});expect(second).toMatchObject({createdCount:0,items:[{id:first.items[0]!.id}]});});
  it('blocks fixture calendars in production and derives overdue todos',async()=>{const service=new FilingService(new MemoryFilingStore(),organizations),calendar=(await service.createCalendar(input,context)).calendar;await expect(service.generate(companyId,{calendarId:calendar.id,usage:'production'},context)).rejects.toMatchObject({status:409,response:{code:'PRODUCTION_CALENDAR_SOURCE_REQUIRED'}});await service.generate(companyId,{calendarId:calendar.id,usage:'test'},context);expect(await service.todos(companyId,context,'2026-10-10')).toMatchObject([{status:'todo',timing:'overdue'}]);});
  it('enforces optimistic forward-only task transitions',async()=>{const service=new FilingService(new MemoryFilingStore(),organizations),calendar=(await service.createCalendar(input,context)).calendar,task=(await service.generate(companyId,{calendarId:calendar.id,usage:'test'},context)).items[0]!;const filed=await service.transition(companyId,task.id,{expectedVersion:1,action:'mark_filed',note:'已在官方平台自主申报'},context);expect(filed).toMatchObject({status:'filed',version:2});await expect(service.transition(companyId,task.id,{expectedVersion:1,action:'mark_paid',note:'过期版本不得写入'},context)).rejects.toMatchObject({response:{code:'FILING_TASK_CHANGED'}});const paid=await service.transition(companyId,task.id,{expectedVersion:2,action:'mark_paid',note:'已在官方渠道完成缴款'},context);expect(paid).toMatchObject({status:'paid',version:3,timing:'completed'});});
  it('stores immutable SOP versions idempotently and rejects content replacement',async()=>{const service=new FilingService(new MemoryFilingStore(),organizations),first=await service.createSop(sopInput,context),same=await service.createSop(sopInput,context);expect(first.created).toBe(true);expect(first.sop.contentHash).toMatch(/^[0-9a-f]{64}$/);expect(same).toMatchObject({created:false,sop:{id:first.sop.id}});await expect(service.createSop({...sopInput,steps:[{...sopInput.steps[0]!,instruction:'试图覆盖相同版本号下的既有不可变步骤'}]},context)).rejects.toMatchObject({status:409,response:{code:'FILING_SOP_VERSION_EXISTS'}});expect(await service.listSops(context)).toHaveLength(1);});
});
