import{describe,expect,it}from'vitest';
import{OrganizationService}from'../src/modules/organization/application/organization.service.js';
import{MemoryOrganizationStore}from'../src/modules/organization/infrastructure/memory-organization.store.js';
import{ProfileScopeService}from'../src/modules/profile-scope/application/profile-scope.service.js';
import{MemoryScopeStore}from'../src/modules/profile-scope/infrastructure/memory-scope.store.js';
import{LedgerSetupService}from'../src/modules/ledger-setup/application/ledger-setup.service.js';
import{MemoryLedgerSetupStore}from'../src/modules/ledger-setup/infrastructure/memory-ledger-setup.store.js';
import{MemoryPeriodReopenStore}from'../src/modules/ledger-setup/infrastructure/memory-period-reopen.store.js';
import{PeriodReopenService}from'../src/modules/ledger-setup/application/period-reopen.service.js';
import{MemoryReviewCaseStore}from'../src/modules/review-case/infrastructure/memory-review-case.store.js';
import{ReviewCaseIntakeService}from'../src/modules/review-case/application/review-case-intake.service.js';

const actorId='10000000-0000-4000-8000-000000000001';
async function fixture(){const organizations=new MemoryOrganizationStore(),scopes=new MemoryScopeStore(),setups=new MemoryLedgerSetupStore();const created=await new OrganizationService(organizations).bootstrap({tenantName:'测试',company:{name:'常州市测试科技有限公司',unifiedSocialCreditCode:'913204001234567890',provinceCode:'32',cityCode:'3204'}},{actorId,traceId:'create'}),context={actorId,tenantId:created.tenantId,traceId:'test'};await new ProfileScopeService(organizations,scopes).evaluate(created.company.id,{entityType:'one_person_llc',vatTaxpayerStatus:'small_scale',vatFilingCycle:'quarterly',incomeTaxCollection:'audit',industry:'modern_service',hasInventory:false,hasBranches:false,hasImportExport:false,hasForeignCurrency:false,hasSpecialVatFivePercent:false,hasDifferenceTax:false,hasCrossRegionPrepayment:false,hasComplexPayroll:false,hasShareholderTransactions:false,hasComplexTaxAdjustments:false,sourceDocumentsComplete:true},context);await new LedgerSetupService(organizations,scopes,setups).create(created.company.id,{accountName:'基本户',accountType:'bank',bankName:'招商银行',accountNumberLast4:'1234',openingBalance:'0',openingBalanceSource:'none',openingBalanceAsOf:'2026-09-30',periodStart:'2026-10-01',periodEnd:'2026-10-31'},context);const requests=new MemoryPeriodReopenStore(setups),reviewCases=new MemoryReviewCaseStore();return{created,context,setups,reviewCases,service:new PeriodReopenService(setups,requests,new ReviewCaseIntakeService(reviewCases))};}

describe('PeriodReopenService',()=>{
  it('only accepts requests for a locked period',async()=>{const{created,context,service}=await fixture();await expect(service.request(created.company.id,{reason:'需要修正遗漏的银行流水'},context)).rejects.toMatchObject({status:409,response:{code:'ACCOUNTING_PERIOD_NOT_LOCKED'}});});
  it('creates one auditable pending request and is idempotent',async()=>{const{created,context,setups,service,reviewCases}=await fixture();await setups.lockCurrentPeriod({tenantId:context.tenantId,companyId:created.company.id,actorId,traceId:'lock',lockedAt:new Date()});const first=await service.request(created.company.id,{reason:'需要修正遗漏的银行流水'},context),second=await service.request(created.company.id,{reason:'重复点击不应新增'},context);expect(first.created).toBe(true);expect(second.created).toBe(false);expect(second.request.id).toBe(first.request.id);expect(await service.list(created.company.id,context)).toHaveLength(1);expect(await reviewCases.list(context.tenantId,created.company.id,{})).toHaveLength(1);});
  it('requires a different reviewer and atomically reopens an approved period',async()=>{const{created,context,setups,service}=await fixture();await setups.lockCurrentPeriod({tenantId:context.tenantId,companyId:created.company.id,actorId,traceId:'lock',lockedAt:new Date()});const{request}=await service.request(created.company.id,{reason:'需要修正遗漏的银行流水'},context);await expect(service.decide(created.company.id,request.id,{decision:'approve',reason:'已核验修正范围及证据',expectedVersion:1},context)).rejects.toMatchObject({status:409,response:{code:'PERIOD_REOPEN_DECISION_REJECTED'}});const reviewer={...context,actorId:'20000000-0000-4000-8000-000000000002',traceId:'review'};const approved=await service.decide(created.company.id,request.id,{decision:'approve',reason:'已核验修正范围及证据',expectedVersion:1},reviewer);expect(approved).toMatchObject({status:'approved',version:2,decidedBy:reviewer.actorId});expect((await setups.find(context.tenantId,created.company.id))?.periodStatus).toBe('open');await expect(service.decide(created.company.id,request.id,{decision:'reject',reason:'重复决定不应成功',expectedVersion:1},reviewer)).rejects.toMatchObject({status:409});});
  it('keeps the period locked after rejection',async()=>{const{created,context,setups,service}=await fixture();await setups.lockCurrentPeriod({tenantId:context.tenantId,companyId:created.company.id,actorId,traceId:'lock',lockedAt:new Date()});const{request}=await service.request(created.company.id,{reason:'申请修改不完整凭证'},context);const rejected=await service.decide(created.company.id,request.id,{decision:'reject',reason:'缺少原始单据，退回补充',expectedVersion:1},{...context,actorId:'20000000-0000-4000-8000-000000000002'});expect(rejected.status).toBe('rejected');expect((await setups.find(context.tenantId,created.company.id))?.periodStatus).toBe('locked');});
});
