import{describe,expect,it}from'vitest';
import{ReviewCaseService}from'../src/modules/review-case/application/review-case.service.js';
import{MemoryReviewCaseStore}from'../src/modules/review-case/infrastructure/memory-review-case.store.js';
import type{ReviewSourceResolver}from'../src/modules/review-case/application/review-source-resolver.js';
const creator='10000000-0000-4000-8000-000000000001',reviewer='20000000-0000-4000-8000-000000000002',companyId='30000000-0000-4000-8000-000000000003',sourceId='40000000-0000-4000-8000-000000000004';
const creatorContext={actorId:creator,tenantId:'50000000-0000-4000-8000-000000000005',traceId:'create'},reviewerContext={...creatorContext,actorId:reviewer,traceId:'review'};
const input={sourceType:'reconciliation_issue' as const,sourceId};
const resolved={riskLevel:'red' as const,blocksFiling:true,summary:'银行余额与账簿余额存在重大差异',createdBy:creator};
const sources:ReviewSourceResolver={resolve:(_tenantId,_companyId,_sourceType,id)=>Promise.resolve(id===sourceId||id==='60000000-0000-4000-8000-000000000006'?resolved:null),documentsExist:(_tenantId,_companyId,ids)=>Promise.resolve(!ids.includes('70000000-0000-4000-8000-000000000007'))};
describe('ReviewCaseService',()=>{
  it('creates idempotently from an authoritative source and exposes queue filters',async()=>{const service=new ReviewCaseService(new MemoryReviewCaseStore(),sources);const first=await service.create(companyId,input,creatorContext),second=await service.create(companyId,input,creatorContext);expect(first.created).toBe(true);expect(first.reviewCase).toMatchObject({riskLevel:'red',blocksFiling:true,summary:'银行余额与账簿余额存在重大差异'});expect(second).toMatchObject({created:false,reviewCase:{id:first.reviewCase.id}});expect(await service.list(companyId,{riskLevel:'red'},creatorContext)).toHaveLength(1);expect(await service.list(companyId,{status:'approved'},creatorContext)).toHaveLength(0);});
  it('runs the append-only document and decision workflow',async()=>{const service=new ReviewCaseService(new MemoryReviewCaseStore(),sources);let item=(await service.create(companyId,input,creatorContext)).reviewCase;item=await service.assign(companyId,item.id,{expectedVersion:1,assignedTo:reviewer,note:'分派给独立专业复核人员'},creatorContext);expect(item).toMatchObject({status:'in_review',version:2,assignedTo:reviewer});item=await service.appendWorkItem(companyId,item.id,{expectedVersion:2,kind:'document_request',content:'请补充银行对账单原件及余额调节表',documentIds:[]},reviewerContext);expect(item).toMatchObject({status:'awaiting_documents',version:3});expect(item.items).toHaveLength(1);item=await service.transition(companyId,item.id,{expectedVersion:3,action:'resume_review',note:'补件已经收齐并完成核验'},reviewerContext);item=await service.appendWorkItem(companyId,item.id,{expectedVersion:4,kind:'workpaper',content:'已复核差异来源，不改变原始对账事实',documentIds:[]},reviewerContext);const approved=await service.decide(companyId,item.id,{expectedVersion:5,decision:'approved',reason:'证据完整，人工复核通过'},reviewerContext);expect(approved).toMatchObject({status:'approved',version:6});expect(approved.items.map(work=>work.kind)).toEqual(['document_request','workpaper']);});
  it('rejects self approval, unauthorized transfers and stale writes',async()=>{const service=new ReviewCaseService(new MemoryReviewCaseStore(),sources);const own=(await service.create(companyId,{...input,assignedTo:creator},creatorContext)).reviewCase;await expect(service.decide(companyId,own.id,{expectedVersion:1,decision:'approved',reason:'不能自行批准自己的案件'},creatorContext)).rejects.toMatchObject({status:409,response:{code:'REVIEW_CASE_ACTION_REJECTED'}});const service2=new ReviewCaseService(new MemoryReviewCaseStore(),sources),item=(await service2.create(companyId,{...input,sourceId:'60000000-0000-4000-8000-000000000006'},creatorContext)).reviewCase;await service2.assign(companyId,item.id,{expectedVersion:1,assignedTo:reviewer,note:'分派独立复核人员处理'},creatorContext);await expect(service2.assign(companyId,item.id,{expectedVersion:2,assignedTo:creator,note:'非当前负责人不得转交'},creatorContext)).rejects.toMatchObject({status:409,response:{code:'REVIEW_CASE_ASSIGNMENT_REJECTED'}});await expect(service2.assign(companyId,item.id,{expectedVersion:1,assignedTo:reviewer,note:'使用过期版本重复分派'},creatorContext)).rejects.toMatchObject({status:409,response:{code:'REVIEW_CASE_CHANGED'}});});
  it('rejects forged sources and cross-scope document references',async()=>{const service=new ReviewCaseService(new MemoryReviewCaseStore(),sources);await expect(service.create(companyId,{...input,sourceId:'80000000-0000-4000-8000-000000000008'},creatorContext)).rejects.toMatchObject({status:404});const item=(await service.create(companyId,input,creatorContext)).reviewCase,assigned=await service.assign(companyId,item.id,{expectedVersion:1,assignedTo:reviewer,note:'分派给独立专业复核人员'},creatorContext);await expect(service.appendWorkItem(companyId,item.id,{expectedVersion:assigned.version,kind:'workpaper',content:'引用不存在的档案应被拒绝',documentIds:['70000000-0000-4000-8000-000000000007']},reviewerContext)).rejects.toMatchObject({status:404});});
});
