/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/v1/companies/{companyId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取当前租户内的公司 */
        readonly get: operations["OrganizationController_getCompany"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting-period/reopen-requests": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出反结账申请 */
        readonly get: operations["AccountingPeriodController_list"];
        readonly put?: never;
        /** 申请反结账；仅创建待复核工单，不直接解锁 */
        readonly post: operations["AccountingPeriodController_request"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/chart-of-accounts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取版本化 V1 科目模板 */
        readonly get: operations["AccountingController_chart"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/ledger": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取正式凭证明细账和本期科目余额 */
        readonly get: operations["AccountingController_ledger"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/period/lock": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 锁定当前会计期间 */
        readonly post: operations["AccountingController_lock"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/reports": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 基于正式账簿生成利润表和资产负债表 */
        readonly get: operations["AccountingController_reports"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/vouchers": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出凭证草稿 */
        readonly get: operations["AccountingController_list"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/vouchers/{voucherId}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 确认平衡凭证并正式入账 */
        readonly post: operations["AccountingController_confirm"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/vouchers/{voucherId}/reverse": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 通过相反分录冲销已确认凭证 */
        readonly post: operations["AccountingController_reverse"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/accounting/vouchers/from-business-event/{eventId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 从已确认业务事项确定性生成凭证草稿 */
        readonly post: operations["AccountingController_generate"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/business-events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出业务事件 */
        readonly get: operations["BusinessEventController_list"];
        readonly put?: never;
        /** 手工创建业务事件草稿 */
        readonly post: operations["BusinessEventController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/business-events/{eventId}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 确认业务事件并冻结该版本 */
        readonly post: operations["BusinessEventController_confirm"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/calculation-runs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出公司的不可变计算运行快照 */
        readonly get: operations["CalculationController_list"];
        readonly put?: never;
        /** 冻结计算输入并选择唯一活动规则；无法确定时返回 DecisionRequired */
        readonly post: operations["CalculationController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/counterparties": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出当前公司的往来单位 */
        readonly get: operations["CounterpartyController_list"];
        readonly put?: never;
        /** 新增客户、供应商、股东或员工 */
        readonly post: operations["CounterpartyController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/documents": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出单据档案 */
        readonly get: operations["DocumentController_list"];
        readonly put?: never;
        /** 上传私有单据并建立首个版本 */
        readonly post: operations["DocumentController_upload"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/documents/{documentId}/links/business-events/{eventId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 将单据证据关联到业务事项 */
        readonly post: operations["DocumentController_link"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/documents/{documentId}/versions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 为单据增加不可覆盖的新版本 */
        readonly post: operations["DocumentController_addVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/documents/{documentId}/versions/{versionId}/content": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取私有单据版本内容 */
        readonly get: operations["DocumentController_content"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/imports/bank-csv": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 上传并校验银行 CSV V1 模板 */
        readonly post: operations["BankImportController_upload"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/imports/bank-csv/{batchId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["BankImportController_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/imports/bank-csv/{batchId}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 确认有效银行流水并生成已确认业务事件 */
        readonly post: operations["BankImportController_confirm"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/invoices": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出当前公司的发票 */
        readonly get: operations["InvoiceController_list"];
        readonly put?: never;
        /** 新增发票草稿 */
        readonly post: operations["InvoiceController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/invoices/{invoiceId}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 确认发票事实 */
        readonly post: operations["InvoiceController_confirm"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/invoices/extractions/mock": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 使用确定性模拟适配器提取发票字段 */
        readonly post: operations["InvoiceController_extract"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/ledger-setup": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取账套初始化结果 */
        readonly get: operations["LedgerSetupController_get"];
        readonly put?: never;
        /** 创建资金账户、期初余额和首个会计期间 */
        readonly post: operations["LedgerSetupController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/reconciliation": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取发票与收付款核销概览 */
        readonly get: operations["ReconciliationController_overview"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/reconciliation/settlements": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 创建发票与收付款的部分或完整核销 */
        readonly post: operations["ReconciliationController_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/scope-evaluations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 保存主体画像并生成适用性结论 */
        readonly post: operations["ProfileScopeController_evaluate"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/companies/{companyId}/scope-evaluations/latest": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取最近一次适用性结论 */
        readonly get: operations["ProfileScopeController_latest"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/policy-sources": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出政策来源 */
        readonly get: operations["PolicyRuleController_listPolicySources"];
        readonly put?: never;
        /** 收录经过官方来源校验的政策文件 */
        readonly post: operations["PolicyRuleController_createPolicySource"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出税务规则包 */
        readonly get: operations["PolicyRuleController_listRulePackages"];
        readonly put?: never;
        /** 创建稳定标识的税务规则包 */
        readonly post: operations["PolicyRuleController_createRulePackage"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/shadow-runs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出规则包的不可变影子计算记录 */
        readonly get: operations["PolicyRuleController_listRuleShadowRuns"];
        readonly put?: never;
        /** 用同一签审样本对比基准与候选规则版本并固化差异证据 */
        readonly post: operations["PolicyRuleController_executeRuleShadowRun"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/shadow-runs/{runId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取影子计算逐样例差异和不可变证据哈希 */
        readonly get: operations["PolicyRuleController_findRuleShadowRun"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出规则包的全部版本 */
        readonly get: operations["PolicyRuleController_listRuleVersions"];
        readonly put?: never;
        /** 创建不可执行的规则草稿版本 */
        readonly post: operations["PolicyRuleController_createRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/activation": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 在计划时间到期后激活规则，并自动替代同规则包的旧活动版本 */
        readonly post: operations["PolicyRuleController_activateRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/approval": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 由独立审批人批准已通过测试的规则版本 */
        readonly post: operations["PolicyRuleController_approveRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/fixture-sets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 列出规则版本的专业签审黄金样本集 */
        readonly get: operations["PolicyRuleController_listGoldenFixtureSets"];
        readonly put?: never;
        /** 由财税复核人登记脱敏、签审且不可变的黄金样本集 */
        readonly post: operations["PolicyRuleController_createGoldenFixtureSet"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/fixture-sets/{fixtureSetId}/executions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 使用版本化计算实现逐例执行黄金样本并生成证据哈希 */
        readonly post: operations["PolicyRuleController_executeGoldenFixtureSet"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/reviews": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 执行工程复核或财税复核，强制职责分离 */
        readonly post: operations["PolicyRuleController_reviewRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/schedule": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 由审批人安排规则版本的未来激活时间 */
        readonly post: operations["PolicyRuleController_scheduleRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/test-evidence": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 登记财税审核人签署的全量黄金样本测试证据 */
        readonly post: operations["PolicyRuleController_recordRuleTestEvidence"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/rule-packages/{rulePackageId}/versions/{ruleVersionId}/withdrawal": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 紧急撤回活动规则版本并保留不可变发布记录 */
        readonly post: operations["PolicyRuleController_withdrawRuleVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/tenants/bootstrap": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 创建租户、所有者成员和首家公司 */
        readonly post: operations["OrganizationController_bootstrap"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly OrganizationController_getCompany: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 当前租户 UUID */
                readonly "x-tenant-id": string;
                /** @description 开发态用户 UUID */
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingPeriodController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingPeriodController_request: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_chart: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_ledger: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_lock: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_reports: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_confirm: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly voucherId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_reverse: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly voucherId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly AccountingController_generate: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly eventId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BusinessEventController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BusinessEventController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BusinessEventController_confirm: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly eventId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly CalculationController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly CalculationController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly CounterpartyController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly CounterpartyController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly DocumentController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly DocumentController_upload: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly DocumentController_link: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly documentId: string;
                readonly eventId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly DocumentController_addVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly documentId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly DocumentController_content: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly documentId: string;
                readonly versionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BankImportController_upload: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BankImportController_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly batchId: string;
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly BankImportController_confirm: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly batchId: string;
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly InvoiceController_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly InvoiceController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly InvoiceController_confirm: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
                readonly invoiceId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly InvoiceController_extract: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly LedgerSetupController_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly LedgerSetupController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly ReconciliationController_overview: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly ReconciliationController_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly ProfileScopeController_evaluate: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly ProfileScopeController_latest: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-tenant-id": string;
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly companyId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_listPolicySources: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_createPolicySource: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_listRulePackages: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_createRulePackage: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_listRuleShadowRuns: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_executeRuleShadowRun: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_findRuleShadowRun: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly runId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_listRuleVersions: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_createRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_activateRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_approveRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_listGoldenFixtureSets: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_createGoldenFixtureSet: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_executeGoldenFixtureSet: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly fixtureSetId: string;
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_reviewRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_scheduleRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_recordRuleTestEvidence: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly PolicyRuleController_withdrawRuleVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "x-user-id": string;
            };
            readonly path: {
                readonly rulePackageId: string;
                readonly ruleVersionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly OrganizationController_bootstrap: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 开发态用户 UUID */
                readonly "x-user-id": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly company: {
                        readonly cityCode: string;
                        readonly name: string;
                        /** @enum {string} */
                        readonly provinceCode: "32";
                        readonly unifiedSocialCreditCode: string;
                    };
                    readonly tenantName: string;
                };
            };
        };
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
