'use client';
import{reviewCaseListResponseSchema,reviewCaseResponseSchema,type ReviewCaseResponse}from'@ledgerly/contracts';
import Link from'next/link';
import{useCallback,useEffect,useMemo,useState,type FormEvent}from'react';
interface Workspace{tenantId:string;companyId:string}
const creatorId='10000000-0000-4000-8000-000000000001',reviewerId='20000000-0000-4000-8000-000000000002';
const statusLabels={open:'待接单',awaiting_documents:'等待补件',in_review:'复核中',approved:'已批准',rejected:'已驳回',cancelled:'已取消'}as const;
const sourceLabels={reconciliation_issue:'勾稽异常',period_reopen_request:'反结账申请'}as const;
function workspace():Workspace|null{try{const raw:unknown=JSON.parse(window.localStorage.getItem('ledgerly.context')??'null');if(!raw||typeof raw!=='object')return null;const value=raw as Partial<Workspace>;return typeof value.tenantId==='string'&&typeof value.companyId==='string'?{tenantId:value.tenantId,companyId:value.companyId}:null}catch{return null}}
function api(){return process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001'}
function headers(context:Workspace,actorId=creatorId,json=false){return{'x-user-id':actorId,'x-tenant-id':context.tenantId,...(json?{'content-type':'application/json'}:{})}}
function sourceHref(item:ReviewCaseResponse){return item.sourceType==='reconciliation_issue'?'/reconciliation':'/accounting'}
async function errorMessage(response:Response,fallback:string){try{const body=await response.json()as{message?:string};return body.message??fallback}catch{return fallback}}

export function ReviewCenter(){
  const[context,setContext]=useState<Workspace|null>(null),[items,setItems]=useState<ReviewCaseResponse[]>([]),[selectedId,setSelectedId]=useState('');
  const[status,setStatus]=useState(''),[risk,setRisk]=useState(''),[onlyMine,setOnlyMine]=useState(false),[ready,setReady]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState<string|null>(null);
  const selected=useMemo(()=>items.find(item=>item.id===selectedId)??items[0]??null,[items,selectedId]);
  const load=useCallback(async(current:Workspace)=>{const query=new URLSearchParams();if(status)query.set('status',status);if(risk)query.set('riskLevel',risk);if(onlyMine)query.set('assignedTo',reviewerId);const response=await fetch(`${api()}/v1/companies/${current.companyId}/review-cases?${query}`,{headers:headers(current,reviewerId)});if(!response.ok)throw new Error('无法读取人工复核队列。');const result=reviewCaseListResponseSchema.parse(await response.json()).items;setItems(result);setSelectedId(id=>result.some(item=>item.id===id)?id:(result[0]?.id??''))},[status,risk,onlyMine]);
  useEffect(()=>{const current=workspace();setContext(current);if(!current){setReady(true);return}void load(current).catch(error=>setMessage(error instanceof Error?error.message:'读取失败。')).finally(()=>setReady(true))},[load]);
  function replace(item:ReviewCaseResponse){setItems(current=>current.map(existing=>existing.id===item.id?item:existing))}
  async function mutate(path:string,body:Record<string,unknown>,actorId?:string){if(!context||!selected)return;setPending(true);setMessage(null);try{const response=await fetch(`${api()}/v1/companies/${context.companyId}/review-cases/${selected.id}/${path}`,{method:'POST',headers:headers(context,actorId??selected.assignedTo??reviewerId,true),body:JSON.stringify(body)});if(!response.ok)throw new Error(await errorMessage(response,response.status===409?'案件状态已经变化，请刷新后重试。':'操作失败。'));replace(reviewCaseResponseSchema.parse(await response.json()));setMessage('操作已保存，案件证据链和版本已经更新。')}catch(error:unknown){setMessage(error instanceof Error?error.message:'操作失败。')}finally{setPending(false)}}
  if(!ready)return <section className="review-shell"><div className="onboarding-card">正在读取复核队列…</div></section>;
  if(!context)return <section className="review-shell"><div className="onboarding-card">请先完成企业建档，再进入人工复核中心。</div></section>;
  return <section className="review-shell">
    <aside className="review-queue"><header><div><p className="eyebrow">运营队列</p><h2>{items.length} 个案件</h2></div><button className="secondary button" disabled={pending} onClick={()=>void load(context)}>刷新</button></header><div className="review-filters"><label>状态<select value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>风险<select value={risk} onChange={event=>setRisk(event.target.value)}><option value="">全部风险</option><option value="red">红色</option><option value="yellow">黄色</option></select></label><label className="mine-filter"><input type="checkbox" checked={onlyMine} onChange={event=>setOnlyMine(event.target.checked)}/>只看分派给我</label></div>{items.length===0?<p className="review-empty">当前筛选条件下没有案件。</p>:<div className="review-list">{items.map(item=><button type="button" className={selected?.id===item.id?'active':''} key={item.id} onClick={()=>setSelectedId(item.id)}><span className={`review-risk ${item.riskLevel}`}>{item.riskLevel==='red'?'红色阻断':'黄色复核'}</span><strong>{item.summary}</strong><small>{sourceLabels[item.sourceType]} · {statusLabels[item.status]} · V{item.version}</small></button>)}</div>}</aside>
    <main className="review-detail">{!selected?<div className="review-empty">选择左侧案件查看详情。</div>:<><header className="review-detail-head"><div><div className="review-badges"><span className={`review-risk ${selected.riskLevel}`}>{selected.riskLevel==='red'?'红色':'黄色'}</span><span className={`review-status ${selected.status}`}>{statusLabels[selected.status]}</span>{selected.blocksFiling&&<span className="review-blocking">阻断申报</span>}</div><h2>{selected.summary}</h2><p>案件 {selected.id} · 版本 {selected.version}</p></div><Link className="secondary button" href={sourceHref(selected)}>下钻{sourceLabels[selected.sourceType]}</Link></header><section className="review-source"><div><span>来源对象</span><code>{selected.sourceId}</code></div><div><span>当前负责人</span><strong>{selected.assignedTo??'尚未分派'}</strong></div><div><span>最后更新</span><strong>{new Date(selected.updatedAt).toLocaleString('zh-CN')}</strong></div></section>{!selected.assignedTo&&<section className="review-action-card"><h3>接单</h3><p>开发态将案件分派给独立复核人。正式角色授权在 R5 落地。</p><button className="primary button" disabled={pending} onClick={()=>void mutate('assign',{expectedVersion:selected.version,assignedTo:reviewerId,note:'运营复核中心接单并开始独立复核'},creatorId)}>分派给开发态复核人</button></section>}{selected.assignedTo&& !['approved','rejected','cancelled'].includes(selected.status)&&<ReviewActions key={selected.id} item={selected} pending={pending} mutate={mutate}/>}<section className="review-timeline"><header><div><p className="eyebrow">追加式证据</p><h3>工作底稿与补件记录</h3></div><span>{selected.items.length} 条</span></header>{selected.items.length===0?<p className="review-empty">尚无底稿或补件记录。</p>:selected.items.map(work=><article key={work.id}><span>{work.kind==='workpaper'?'工作底稿':'补件请求'}</span><div><strong>{work.content}</strong><small>{new Date(work.createdAt).toLocaleString('zh-CN')} · {work.createdBy}</small>{work.documentIds.length>0&&<p>引用文档：{work.documentIds.map(id=><code key={id}>{id}</code>)}</p>}</div>{work.documentIds.length>0&&<Link href="/documents">查看档案</Link>}</article>)}</section>{message&&<p className={message.includes('失败')||message.includes('变化')||message.includes('不能')?'form-error review-message':'form-success review-message'} role="status">{message}</p>}</>}</main>
  </section>
}

function ReviewActions({item,pending,mutate}:{item:ReviewCaseResponse;pending:boolean;mutate:(path:string,body:Record<string,unknown>,actorId?:string)=>Promise<void>}){
  const[kind,setKind]=useState<'workpaper'|'document_request'>('workpaper'),[content,setContent]=useState(''),[documentIds,setDocumentIds]=useState(''),[reason,setReason]=useState(''),[nextAssignee,setNextAssignee]=useState('');
  function append(event:FormEvent){event.preventDefault();const ids=documentIds.split(/[\s,，]+/).filter(Boolean);void mutate('work-items',{expectedVersion:item.version,kind,content,documentIds:ids}).then(()=>{setContent('');setDocumentIds('')})}
  return <section className="review-actions"><form className="review-action-card" onSubmit={append}><h3>追加复核记录</h3><label>记录类型<select value={kind} onChange={event=>setKind(event.target.value as typeof kind)}><option value="workpaper">工作底稿</option><option value="document_request">补件请求</option></select></label><label>内容<textarea value={content} onChange={event=>setContent(event.target.value)} minLength={5} maxLength={4000} rows={4} required placeholder="记录核验过程、结论依据或需要补充的材料"/></label><label>Document UUID（可选）<input value={documentIds} onChange={event=>setDocumentIds(event.target.value)} placeholder="多个 UUID 用逗号分隔"/><small>服务端验证档案归属，只保存引用，不复制原文件。</small></label><button className="primary button" disabled={pending}>{kind==='workpaper'?'追加工作底稿':'发出补件请求'}</button></form><div className="review-action-card decision-card"><h3>案件流转与决定</h3><label>转交复核人 UUID<input value={nextAssignee} onChange={event=>setNextAssignee(event.target.value)} placeholder="输入另一位复核人的 UUID"/></label><button className="secondary button" disabled={pending||!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(nextAssignee)} onClick={()=>void mutate('assign',{expectedVersion:item.version,assignedTo:nextAssignee,note:'转交其他专业复核人员继续处理'})}>转交案件</button>{item.status==='awaiting_documents'&&<button className="secondary button" disabled={pending} onClick={()=>void mutate('transitions',{expectedVersion:item.version,action:'resume_review',note:'补充材料已经收齐，恢复专业复核'})}>补件收齐，恢复复核</button>}<label>决定依据<textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={5} maxLength={2000} rows={4} placeholder="写明证据、判断和风险边界"/></label><div className="review-decision-buttons"><button className="primary button" disabled={pending||item.status!=='in_review'||reason.trim().length<5} onClick={()=>void mutate('decision',{expectedVersion:item.version,decision:'approved',reason})}>批准</button><button className="secondary button danger" disabled={pending||item.status!=='in_review'||reason.trim().length<5} onClick={()=>void mutate('decision',{expectedVersion:item.version,decision:'rejected',reason})}>驳回</button></div><button className="secondary button" disabled={pending||reason.trim().length<5} onClick={()=>void mutate('transitions',{expectedVersion:item.version,action:'cancel',note:reason})}>取消案件</button><p>批准仅记录复核结论，不会修改来源事实或解除勾稽阻断。</p></div></section>
}
