import { Injectable } from '@nestjs/common';
import { VoucherStatus } from '@ledgerly/domain';
import type { ConfirmVoucherRecord, ReverseVoucherRecord, SavedVoucher, SaveVoucherRecord, VoucherStore } from '../application/voucher-store.js';

@Injectable()
export class MemoryVoucherStore implements VoucherStore{
  private readonly records=new Map<string,SavedVoucher[]>();
  save(record:SaveVoucherRecord):Promise<SavedVoucher>{const saved=Object.freeze({id:record.id,companyId:record.companyId,...record.voucher,entries:record.voucher.entries.map((entry,index)=>Object.freeze({id:record.entryIds[index]!,...entry})),createdAt:record.createdAt,createdBy:record.actorId});const key=this.key(record.tenantId,record.companyId);this.records.set(key,[...(this.records.get(key)??[]),saved]);return Promise.resolve(saved);}
  list(tenantId:string,companyId:string):Promise<readonly SavedVoucher[]>{return Promise.resolve([...(this.records.get(this.key(tenantId,companyId))??[])].sort((a,b)=>b.voucherDate.localeCompare(a.voucherDate)));}
  findById(tenantId:string,companyId:string,voucherId:string):Promise<SavedVoucher|null>{return Promise.resolve((this.records.get(this.key(tenantId,companyId))??[]).find(item=>item.id===voucherId)??null);}
  findBySource(tenantId:string,companyId:string,eventId:string,ruleVersion:string):Promise<SavedVoucher|null>{return Promise.resolve((this.records.get(this.key(tenantId,companyId))??[]).find(item=>item.sourceBusinessEventId===eventId&&item.ruleVersion===ruleVersion)??null);}
  confirm(record:ConfirmVoucherRecord):Promise<SavedVoucher|null>{const key=this.key(record.tenantId,record.companyId),items=this.records.get(key)??[],index=items.findIndex(item=>item.id===record.voucherId&&item.status===VoucherStatus.Draft&&item.version===record.expectedVersion);if(index<0)return Promise.resolve(null);const current=items[index]!;const saved=Object.freeze({...current,status:VoucherStatus.Confirmed,version:current.version+1,confirmedAt:record.confirmedAt});this.records.set(key,items.map((item,i)=>i===index?saved:item));return Promise.resolve(saved);}
  reverse(record:ReverseVoucherRecord):Promise<SavedVoucher|null>{const key=this.key(record.tenantId,record.companyId),items=this.records.get(key)??[],index=items.findIndex(item=>item.id===record.originalVoucherId&&item.status===VoucherStatus.Confirmed&&item.version===record.expectedVersion);if(index<0||items.some(item=>item.reversalOfVoucherId===record.originalVoucherId))return Promise.resolve(null);const original=items[index]!;const reversed=Object.freeze({...original,status:VoucherStatus.Reversed,version:original.version+1,reversedAt:record.reversedAt});const reversal=Object.freeze({id:record.reversalId,companyId:record.companyId,...record.reversal,reversalOfVoucherId:record.originalVoucherId,entries:record.reversal.entries.map((entry,i)=>Object.freeze({id:record.reversalEntryIds[i]!,...entry})),createdAt:record.reversedAt,createdBy:record.actorId,confirmedAt:record.reversedAt});this.records.set(key,[...items.map((item,i)=>i===index?reversed:item),reversal]);return Promise.resolve(reversal);}
  private key(tenantId:string,companyId:string){return`${tenantId}:${companyId}`;}
}
