import { Inject,Injectable } from '@nestjs/common';
import { and,asc,desc,eq } from 'drizzle-orm';
import { Money,VoucherStatus } from '@ledgerly/domain';
import { randomUUID } from 'node:crypto';
import { DATABASE,type Database } from '../../../infrastructure/database/database.provider.js';
import { auditEvents,outboxEvents,voucherEntries,vouchers } from '../../../infrastructure/database/schema.js';
import type { ConfirmVoucherRecord,ReverseVoucherRecord,SavedVoucher,SaveVoucherRecord,VoucherStore } from '../application/voucher-store.js';

@Injectable()
export class PostgresVoucherStore implements VoucherStore{
  constructor(@Inject(DATABASE)private readonly db:Database){}
  async save(record:SaveVoucherRecord):Promise<SavedVoucher>{await this.db.transaction(async tx=>{await tx.insert(vouchers).values({id:record.id,tenantId:record.tenantId,companyId:record.companyId,voucherDate:record.voucher.voucherDate,summary:record.voucher.summary,sourceBusinessEventId:record.voucher.sourceBusinessEventId,templateVersion:record.voucher.templateVersion,ruleVersion:record.voucher.ruleVersion,status:record.voucher.status,version:record.voucher.version,createdAt:record.createdAt,createdBy:record.actorId,updatedAt:record.createdAt,updatedBy:record.actorId});await tx.insert(voucherEntries).values(record.voucher.entries.map((entry,index)=>({id:record.entryIds[index]!,voucherId:record.id,lineNumber:entry.lineNumber,accountCode:entry.accountCode,accountName:entry.accountName,side:entry.side,amount:entry.amount.toString()})));await tx.insert(auditEvents).values({id:randomUUID(),tenantId:record.tenantId,actorId:record.actorId,action:'voucher.draft.generate',resourceType:'voucher',resourceId:record.id,outcome:'success',traceId:record.traceId,metadata:{sourceBusinessEventId:record.voucher.sourceBusinessEventId,ruleVersion:record.voucher.ruleVersion}});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId:record.tenantId,eventType:'voucher.draft_generated.v1',aggregateType:'voucher',aggregateId:record.id,payload:{voucherId:record.id,companyId:record.companyId,sourceBusinessEventId:record.voucher.sourceBusinessEventId},occurredAt:record.createdAt});});return{id:record.id,companyId:record.companyId,...record.voucher,entries:record.voucher.entries.map((entry,index)=>({id:record.entryIds[index]!,...entry})),createdAt:record.createdAt,createdBy:record.actorId};}
  async list(tenantId:string,companyId:string):Promise<readonly SavedVoucher[]>{const rows=await this.db.select().from(vouchers).where(and(eq(vouchers.tenantId,tenantId),eq(vouchers.companyId,companyId))).orderBy(desc(vouchers.voucherDate),desc(vouchers.createdAt));return Promise.all(rows.map(row=>this.hydrate(row)));}
  async findById(tenantId:string,companyId:string,voucherId:string):Promise<SavedVoucher|null>{const[row]=await this.db.select().from(vouchers).where(and(eq(vouchers.tenantId,tenantId),eq(vouchers.companyId,companyId),eq(vouchers.id,voucherId))).limit(1);return row?this.hydrate(row):null;}
  async findBySource(tenantId:string,companyId:string,eventId:string,ruleVersion:string):Promise<SavedVoucher|null>{const[row]=await this.db.select().from(vouchers).where(and(eq(vouchers.tenantId,tenantId),eq(vouchers.companyId,companyId),eq(vouchers.sourceBusinessEventId,eventId),eq(vouchers.ruleVersion,ruleVersion))).limit(1);return row?this.hydrate(row):null;}
  async confirm(record:ConfirmVoucherRecord):Promise<SavedVoucher|null>{const[updated]=await this.db.transaction(async tx=>{const rows=await tx.update(vouchers).set({status:VoucherStatus.Confirmed,version:record.expectedVersion+1,confirmedAt:record.confirmedAt,updatedAt:record.confirmedAt,updatedBy:record.actorId}).where(and(eq(vouchers.tenantId,record.tenantId),eq(vouchers.companyId,record.companyId),eq(vouchers.id,record.voucherId),eq(vouchers.status,VoucherStatus.Draft),eq(vouchers.version,record.expectedVersion))).returning();if(!rows[0])return[];await tx.insert(auditEvents).values({id:randomUUID(),tenantId:record.tenantId,actorId:record.actorId,action:'voucher.confirm',resourceType:'voucher',resourceId:record.voucherId,outcome:'success',traceId:record.traceId,metadata:{version:record.expectedVersion+1}});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId:record.tenantId,eventType:'voucher.confirmed.v1',aggregateType:'voucher',aggregateId:record.voucherId,payload:{voucherId:record.voucherId,companyId:record.companyId},occurredAt:record.confirmedAt});return rows;});return updated?this.hydrate(updated):null;}
  async reverse(record:ReverseVoucherRecord):Promise<SavedVoucher|null>{const created=await this.db.transaction(async tx=>{const[updated]=await tx.update(vouchers).set({status:VoucherStatus.Reversed,version:record.expectedVersion+1,reversedAt:record.reversedAt,updatedAt:record.reversedAt,updatedBy:record.actorId}).where(and(eq(vouchers.tenantId,record.tenantId),eq(vouchers.companyId,record.companyId),eq(vouchers.id,record.originalVoucherId),eq(vouchers.status,VoucherStatus.Confirmed),eq(vouchers.version,record.expectedVersion))).returning();if(!updated)return null;const[inserted]=await tx.insert(vouchers).values({id:record.reversalId,tenantId:record.tenantId,companyId:record.companyId,voucherDate:record.reversal.voucherDate,summary:record.reversal.summary,sourceBusinessEventId:record.reversal.sourceBusinessEventId,templateVersion:record.reversal.templateVersion,ruleVersion:record.reversal.ruleVersion,status:record.reversal.status,version:record.reversal.version,confirmedAt:record.reversedAt,reversalOfVoucherId:record.originalVoucherId,createdAt:record.reversedAt,createdBy:record.actorId,updatedAt:record.reversedAt,updatedBy:record.actorId}).returning();await tx.insert(voucherEntries).values(record.reversal.entries.map((entry,index)=>({id:record.reversalEntryIds[index]!,voucherId:record.reversalId,lineNumber:entry.lineNumber,accountCode:entry.accountCode,accountName:entry.accountName,side:entry.side,amount:entry.amount.toString()})));await tx.insert(auditEvents).values({id:randomUUID(),tenantId:record.tenantId,actorId:record.actorId,action:'voucher.reverse',resourceType:'voucher',resourceId:record.originalVoucherId,outcome:'success',traceId:record.traceId,metadata:{reversalVoucherId:record.reversalId}});await tx.insert(outboxEvents).values({id:randomUUID(),tenantId:record.tenantId,eventType:'voucher.reversed.v1',aggregateType:'voucher',aggregateId:record.originalVoucherId,payload:{voucherId:record.originalVoucherId,reversalVoucherId:record.reversalId,companyId:record.companyId},occurredAt:record.reversedAt});return inserted??null;});return created?this.hydrate(created):null;}
  private async hydrate(row:typeof vouchers.$inferSelect):Promise<SavedVoucher>{const entries=await this.db.select().from(voucherEntries).where(eq(voucherEntries.voucherId,row.id)).orderBy(asc(voucherEntries.lineNumber));return{id:row.id,companyId:row.companyId,voucherDate:row.voucherDate,summary:row.summary,sourceBusinessEventId:row.sourceBusinessEventId,templateVersion:row.templateVersion,ruleVersion:row.ruleVersion,status:row.status as VoucherStatus,version:row.version,entries:entries.map(entry=>({id:entry.id,lineNumber:entry.lineNumber,accountCode:entry.accountCode,accountName:entry.accountName,side:entry.side as 'debit'|'credit',amount:Money.from(entry.amount)})),createdAt:row.createdAt,createdBy:row.createdBy,confirmedAt:row.confirmedAt??undefined,reversedAt:row.reversedAt??undefined,reversalOfVoucherId:row.reversalOfVoucherId??undefined};}
}
